CREATE TABLE PROGRM_CHANGE_DETAIL2
(
	PROGRM_FILE_NM        VARCHAR2(60)  NOT NULL ,
	REQUST_NO             NUMBER(10)  NOT NULL ,
	RQESTER_ID            VARCHAR2(20)  NOT NULL ,
	CHANGE_REQUST_CN      VARCHAR2(1000)  NULL ,
	REQUST_PROCESS_CN     CLOB  NULL ,
	OPETR_ID              VARCHAR2(20)  NULL ,
	PROCESS_STTUS_CODE    VARCHAR2(15)  NOT NULL ,
	PROCESS_DE            CHAR(20)  NULL ,
	RQESTDE               CHAR(20)  NULL ,
	REQUST_SJ             VARCHAR2(60)  NOT NULL ,
CONSTRAINT  PROGRM_CHANGE_DETAIL_PK PRIMARY KEY (PROGRM_FILE_NM,REQUST_NO),
CONSTRAINT  PROGRM_CHANGE_DETAIL_FK1 FOREIGN KEY (PROGRM_FILE_NM) REFERENCES PROGRM_LIST(PROGRM_FILE_NM) ON DELETE CASCADE
);

CREATE TABLE POPUP_MANAGE
(
	POPUP_ID              VARCHAR2(20)  NOT NULL ,
	POPUP_SJ_NM           VARCHAR2(1024)  NULL ,
	FILE_URL              VARCHAR2(1024)  NULL ,
	POPUP_WIDTH_LC        VARCHAR2(20)  NULL ,
	POPUP_WIDTH_SIZE      NUMBER  NULL ,
	NTCE_BGNDE            CHAR(20)  NULL ,
	NTCE_ENDDE            CHAR(20)  NULL ,
	STOPVEW_SETUP_AT      CHAR(1)  NULL ,
	NTCE_AT               CHAR(1)  NULL ,
	POPUP_VRTICL_LC       VARCHAR2(20)  NULL ,
	POPUP_VRTICL_SIZE     NUMBER  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
CONSTRAINT  COMTNPOPUPMANAGE_PK PRIMARY KEY (POPUP_ID)
);
CREATE TABLE LOGIN_SCRIN_IMAGE
(
	IMAGE_ID              CHAR(20)  NOT NULL ,
	IMAGE_NM              VARCHAR2(20)  NOT NULL ,
	REFLCT_AT             CHAR(1)  NOT NULL ,
	IMAGE                 VARCHAR2(60)  NOT NULL ,
	IMAGE_DC              VARCHAR2(200)  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	IMAGE_FILE            VARCHAR2(60)  NULL ,
CONSTRAINT  LOGIN_SCRIN_IMAGE_PK PRIMARY KEY (IMAGE_ID)
);


CREATE TABLE EMAIL_DSPTCH_MANAGE
(
	MSSAGE_ID             VARCHAR2(20)  NOT NULL ,
	EMAIL_CN              CLOB  NULL ,
	SNDR                  VARCHAR2(50)  NOT NULL ,
	RCVER                 VARCHAR2(50)  NOT NULL ,
	SJ                    VARCHAR2(60)  NOT NULL ,
	SNDNG_RESULT_CODE     CHAR(1)  NULL ,
	DSPTCH_DT             CHAR(20)  NOT NULL ,
	ATCH_FILE_ID          CHAR(20)  NULL ,
CONSTRAINT  EMAIL_DSPTCH_MANAGE_PK PRIMARY KEY (MSSAGE_ID),
CONSTRAINT  EMAIL_DSPTCH_MANAGE_FK1 FOREIGN KEY (ATCH_FILE_ID) REFERENCES ATCH_FILE(ATCH_FILE_ID) ON DELETE SET NULL
);

CREATE TABLE STATS
(
	STATS_ID              CHAR(18)  NOT NULL ,
	NTCE_CO               NUMBER(10)  NULL ,
	AVRG_RDCNT            NUMBER(10)  NULL ,
	TOP_RDCNT             NUMBER(10)  NULL ,
	MUMM_RDCNT            NUMBER(10)  NULL ,
	TOP_NTCR_ID           VARCHAR2(20)  NULL ,
CONSTRAINT  STATS_PK PRIMARY KEY (STATS_ID)
);

CREATE TABLE SITE_LIST
(
	SITE_ID               CHAR(20)  NOT NULL ,
	SITE_NM               VARCHAR2(100)  NULL ,
	SITE_URL              VARCHAR2(100)  NULL ,
	SITE_DC               VARCHAR2(1000)  NULL ,
	SITE_THEMA_CL_CODE    VARCHAR2(2)  NULL ,
	ACTVTY_AT             CHAR(1)  NULL ,
	USE_AT                CHAR(1)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
CONSTRAINT  SITE_LIST_PK PRIMARY KEY (SITE_ID)
);

CREATE TABLE RECENT_SRCHWRD_MANAGE
(
	SRCHWRD_MANAGE_ID     CHAR(20)  NOT NULL ,
	SRCHWRD_MANAGE_NM     VARCHAR2(255)  NULL ,
	SRCHWRD_CONECT_URL    VARCHAR2(255)  NULL ,
	USER_SEARCH_AT        CHAR(1)  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
CONSTRAINT  RECENT_SRCHWRD_MANAGE_PK PRIMARY KEY (SRCHWRD_MANAGE_ID)
);

CREATE TABLE RECENT_SRCHWRD
(
	SRCHWRD_MANAGE_ID     CHAR(20)  NOT NULL ,
	RECENT_SRCHWRD_ID     CHAR(20)  NOT NULL ,
	RECENT_SRCHWRD_NM     VARCHAR2(255)  NULL ,
	RECENT_SRCHWRD_CO     NUMBER(20)  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
CONSTRAINT  RECENT_SRCHWRD_PK PRIMARY KEY (RECENT_SRCHWRD_ID),
CONSTRAINT  RECENT_SRCHWRD_FK1 FOREIGN KEY (SRCHWRD_MANAGE_ID) REFERENCES COMTNRECENTSRCHWRDMANAGE(SRCHWRD_MANAGE_ID)
);

CREATE TABLE PROXY
(
	PROXY_ID              CHAR(20)  NOT NULL ,
	PROXY_NM              VARCHAR2(60)  NULL ,
	PROXY_IP              VARCHAR2(23)  NULL ,
	PROXY_PORT            VARCHAR2(10)  NULL ,
	TRGET_SVC_NM          VARCHAR2(255)  NULL ,
	SVC_DC                VARCHAR2(2000)  NULL ,
	SVC_IP                VARCHAR2(23)  NULL ,
	SVC_PORT              VARCHAR2(10)  NULL ,
	SVC_STTUS             CHAR(2)  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
CONSTRAINT  PROXY_PK PRIMARY KEY (PROXY_ID)
);

CREATE TABLE PROXY_LOG
(
	PROXY_ID              CHAR(20)  NOT NULL ,
	CLNT_IP               VARCHAR2(23)  NULL ,
	CLNT_PORT             VARCHAR2(10)  NULL ,
	CONECT_TIME           DATE  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	LOG_ID                CHAR(20)  NOT NULL ,
CONSTRAINT  PROXY_LOG_PK PRIMARY KEY (PROXY_ID,LOG_ID),
CONSTRAINT  PROXY_LOG_FK1 FOREIGN KEY (PROXY_ID) REFERENCES PROXY(PROXY_ID)
);

CREATE TABLE MAIN_IMAGE
(
	IMAGE_ID              CHAR(20)  NOT NULL ,
	IMAGE_NM              VARCHAR2(20)  NOT NULL ,
	IMAGE                 VARCHAR2(60)  NOT NULL ,
	IMAGE_DC              VARCHAR2(200)  NULL ,
	REFLCT_AT             CHAR(1)  NOT NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	IMAGE_FILE            VARCHAR2(60)  NULL ,
CONSTRAINT  MAIN_IMAGE_PK PRIMARY KEY (IMAGE_ID)
);

CREATE TABLE UNITY_LINK
(
	UNITY_LINK_ID         CHAR(20)  NOT NULL ,
	UNITY_LINK_GROUP      VARCHAR2(255)  NULL ,
	UNITY_LINK_NM         VARCHAR2(255)  NULL ,
	UNITY_LINK_URL        VARCHAR2(255)  NULL ,
	UNITY_LINK_DC         VARCHAR2(2500)  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	UNITY_LINK_SE_CODE    CHAR(3)  NULL ,
CONSTRAINT  UNITY_LINK_PK PRIMARY KEY (UNITY_LINK_ID)
);

CREATE TABLE SYS_LOG
(
	REQUST_ID             VARCHAR2(20)  NOT NULL ,
	JOB_SE_CODE           CHAR(3)  NULL ,
	INSTT_CODE            CHAR(7)  NULL ,
	OCCRRNC_DE            CHAR(20)  NULL ,
	RQESTER_IP            VARCHAR2(23)  NULL ,
	RQESTER_ID            VARCHAR2(20)  NULL ,
	TRGET_MENU_NM         VARCHAR2(255)  NULL ,
	SVC_NM                VARCHAR2(255)  NULL ,
	METHOD_NM             VARCHAR2(60)  NULL ,
	PROCESS_SE_CODE       CHAR(3)  NULL ,
	PROCESS_CO            NUMBER(10)  NULL ,
	PROCESS_TIME          VARCHAR2(14)  NULL ,
	RSPNS_CODE            CHAR(3)  NULL ,
	ERROR_SE              CHAR(1)  NULL ,
	ERROR_CO              NUMBER(10)  NULL ,
	ERROR_CODE            CHAR(3)  NULL ,
CONSTRAINT  SYS_LOG_PK PRIMARY KEY (REQUST_ID)
);

CREATE TABLE COMMENT
(
	NTT_ID                NUMBER(20)  NOT NULL ,
	BBS_ID                CHAR(20)  NOT NULL ,
	ANSWER_NO             NUMBER(20)  NOT NULL ,
	WRTER_ID              VARCHAR2(20)  NULL ,
	WRTER_NM              VARCHAR2(20)  NULL ,
	ANSWER                VARCHAR2(200)  NULL ,
	USE_AT                CHAR(1)  NOT NULL ,
	FRST_REGIST_PNTTM     DATE  NOT NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NOT NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	PASSWORD              VARCHAR2(200)  NULL ,
CONSTRAINT  COMMENT_PK PRIMARY KEY (NTT_ID,BBS_ID,ANSWER_NO),
CONSTRAINT  COMMENT_FK1 FOREIGN KEY (NTT_ID,BBS_ID) REFERENCES BBS(NTT_ID,BBS_ID)
);

CREATE TABLE RECOMEND_SITE
(
	RECOMEND_SITE_ID      CHAR(20)  NOT NULL ,
	RECOMEND_SITE_NM      VARCHAR2(100)  NULL ,
	RECOMEND_SITE_URL     VARCHAR2(255)  NULL ,
	RECOMEND_SITE_DC      VARCHAR2(1000)  NULL ,
	RECOMEND_RESN_CN      VARCHAR2(1000)  NULL ,
	RECOMEND_CONFM_AT     CHAR(1)  NULL ,
	CONFM_DE              CHAR(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
CONSTRAINT  RECOMEND_SITE_PK PRIMARY KEY (RECOMEND_SITE_ID)
);
CREATE TABLE INTNET_SVC
(
	INTNET_SVC_ID         CHAR(20)  NOT NULL ,
	INTNET_SVC_NM         VARCHAR2(20)  NOT NULL ,
	INTNET_SVC_DC         VARCHAR2(200)  NULL ,
	REFLCT_AT             CHAR(1)  NOT NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
CONSTRAINT  INTNET_SVC_PK PRIMARY KEY (INTNET_SVC_ID)
);
CREATE TABLE CLUB
(
	CLB_ID                CHAR(20)  NOT NULL ,
	CMMNTY_ID             CHAR(20)  NOT NULL ,
	CLB_NM                VARCHAR2(255)  NOT NULL ,
	CLB_INTRCN            VARCHAR2(2400)  NULL ,
	USE_AT                CHAR(1)  NOT NULL ,
	REGIST_SE_CODE        CHAR(6)  NULL ,
	TMPLAT_ID             CHAR(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NOT NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NOT NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
CONSTRAINT  CLUB_PK PRIMARY KEY (CLB_ID,CMMNTY_ID)
);


CREATE TABLE CLUB_USER
(
	CLB_ID                CHAR(20)  NOT NULL ,
	CMMNTY_ID             CHAR(20)  NOT NULL ,
	OPRTR_AT              CHAR(1)  NOT NULL ,
	SBSCRB_DE             DATE  NULL ,
	SECSN_DE              CHAR(20)  NULL ,
	USE_AT                CHAR(1)  NOT NULL ,
	FRST_REGIST_PNTTM     DATE  NOT NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NOT NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	EMPLYR_ID             VARCHAR2(20)  NOT NULL ,
CONSTRAINT  CLUB_USER_PK PRIMARY KEY (CLB_ID,CMMNTY_ID,EMPLYR_ID),
CONSTRAINT  CLUB_USER_FK1 FOREIGN KEY (CLB_ID,CMMNTY_ID) REFERENCES CLUB(CLB_ID,CMMNTY_ID)
);

CREATE TABLE BACKUP_OPERT
(
	BACKUP_OPERT_ID       VARCHAR2(20)  NOT NULL ,
	BACKUP_OPERT_NM       VARCHAR2(60)  NULL ,
	BACKUP_ORGINL_DRCTRY  VARCHAR2(255)  NULL ,
	BACKUP_STRE_DRCTRY    VARCHAR2(255)  NULL ,
	CMPRS_SE              VARCHAR2(2)  NULL ,
	EXECUT_CYCLE          VARCHAR2(2)  NULL ,
	EXECUT_SCHDUL_DE      CHAR(20)  NULL ,
	EXECUT_SCHDUL_HOUR    CHAR(2)  NULL ,
	EXECUT_SCHDUL_MNT     CHAR(2)  NULL ,
	EXECUT_SCHDUL_SECND   CHAR(2)  NULL ,
	USE_AT                CHAR(1)  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NOT NULL ,
CONSTRAINT  BACKUP_OPERT_PK PRIMARY KEY (BACKUP_OPERT_ID)
);
CREATE TABLE BACKUP_SCHDUL_DFK
(
	BACKUP_OPERT_ID       VARCHAR2(20)  NOT NULL ,
	EXECUT_SCHDUL_DFK_SE  CHAR(1)  NOT NULL ,
CONSTRAINT  COMTNBACKUPSCHDULDFK_PK PRIMARY KEY (BACKUP_OPERT_ID,EXECUT_SCHDUL_DFK_SE),
CONSTRAINT  BACKUP_SCHDUL_DFK_FK1 FOREIGN KEY (BACKUP_OPERT_ID) REFERENCES BACKUP_OPERT(BACKUP_OPERT_ID)
);

CREATE TABLE COMMUNTY
(
	CMMNTY_ID             CHAR(20)  NOT NULL ,
	CMMNTY_NM             VARCHAR2(255)  NOT NULL ,
	CMMNTY_INTRCN         VARCHAR2(2400)  NULL ,
	USE_AT                CHAR(1)  NOT NULL ,
	REGIST_SE_CODE        CHAR(6)  NULL ,
	TMPLAT_ID             CHAR(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NOT NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NOT NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
CONSTRAINT  COMMUNTY_PK PRIMARY KEY (CMMNTY_ID)
);

CREATE TABLE COMMUNTY_USER
(
	CMMNTY_ID             CHAR(20)  NOT NULL ,
	EMPLYR_ID             VARCHAR2(20)  NOT NULL ,
	MNGR_AT               CHAR(1)  NOT NULL ,
	SBSCRB_DE             DATE  NULL ,
	SECSN_DE              CHAR(20)  NULL ,
	USE_AT                CHAR(1)  NULL ,
	FRST_REGIST_PNTTM     DATE  NOT NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NOT NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
CONSTRAINT  COMMUNTY_USER_PK PRIMARY KEY (CMMNTY_ID,EMPLYR_ID),
CONSTRAINT  COMMUNTY_USER_FK1 FOREIGN KEY (CMMNTY_ID) REFERENCES COMMUNITY(CMMNTY_ID)
);

CREATE TABLE ADMINIST_CODE
(
	ADMINIST_ZONE_SE      CHAR(1)  NOT NULL ,
	ADMINIST_ZONE_CODE    VARCHAR2(10)  NOT NULL ,
	USE_AT                CHAR(1)  NOT NULL ,
	ADMINIST_ZONE_NM      VARCHAR2(60)  NULL ,
	UPPER_ADMINIST_ZONE_CODE  VARCHAR2(10)  NULL ,
	CREAT_DE              CHAR(20)  NULL ,
	ABL_DE                CHAR(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
CONSTRAINT  ADMINIST_CODE_PK PRIMARY KEY (ADMINIST_ZONE_SE,ADMINIST_ZONE_CODE)
);
CREATE TABLE USER_LOG
(
	OCCRRNC_DE            CHAR(20)  NOT NULL ,
	RQESTER_ID            VARCHAR2(20)  NOT NULL ,
	SVC_NM                VARCHAR2(255)  NOT NULL ,
	METHOD_NM             VARCHAR2(60)  NOT NULL ,
	CREAT_CO              NUMBER(10)  NULL ,
	UPDT_CO               NUMBER(10)  NULL ,
	RDCNT                 NUMBER(10)  NULL ,
	DELETE_CO             NUMBER(10)  NULL ,
	OUTPT_CO              NUMBER(10)  NULL ,
	ERROR_CO              NUMBER(10)  NULL ,
CONSTRAINT  USER_LOG_PK PRIMARY KEY (OCCRRNC_DE,RQESTER_ID,SVC_NM,METHOD_NM)
);
CREATE TABLE TRSMRCV_LOG_SUMMARY
(
	OCCRRNC_DE            CHAR(20)  NOT NULL ,
	TRSMRCV_SE_CODE       CHAR(3)  NOT NULL ,
	PROVD_INSTT_ID        CHAR(8)  NOT NULL ,
	PROVD_SYS_ID          CHAR(8)  NOT NULL ,
	PROVD_SVC_ID          CHAR(8)  NOT NULL ,
	REQUST_INSTT_ID       CHAR(8)  NOT NULL ,
	REQUST_SYS_ID         CHAR(8)  NOT NULL ,
	RDCNT                 NUMBER(10)  NULL ,
	ERROR_CO              NUMBER(10)  NULL ,
CONSTRAINT  TRSMRCV_LOG_SUMMARY_PK PRIMARY KEY (OCCRRNC_DE,TRSMRCV_SE_CODE,PROVD_INSTT_ID,PROVD_SYS_ID,PROVD_SVC_ID,REQUST_INSTT_ID,REQUST_SYS_ID)
);

CREATE TABLE BSS_UMMARY
(
	OCCRRNC_DE            CHAR(20)  NOT NULL ,
	STATS_SE              VARCHAR2(10)  NOT NULL ,
	DETAIL_STATS_SE       VARCHAR2(10)  NOT NULL ,
	CREAT_CO              NUMBER(10)  NULL ,
	TOT_RDCNT             NUMBER(10)  NULL ,
	AVRG_RDCNT            NUMBER(10)  NULL ,
	TOP_INQIRE_BBSCTT_ID  VARCHAR2(20)  NULL ,
	MUMM_INQIRE_BBSCTT_ID  VARCHAR2(20)  NULL ,
	TOP_NTCR_ID           VARCHAR2(20)  NULL ,
CONSTRAINT  BSS_UMMARY_PK PRIMARY KEY (OCCRRNC_DE,STATS_SE,DETAIL_STATS_SE)
);
CREATE TABLE RDNMADR_ZIP
(
	RDMN_CODE             VARCHAR2(12) NOT NULL,
	SN                    NUMBER(10) NOT NULL,
	CTPRVN_NM             VARCHAR2(20) NULL,
	SIGNGU_NM             VARCHAR2(20) NULL,
	RDMN                  VARCHAR2(60) NULL,
	BDNBR_MNNM            VARCHAR2(5) NULL,
	BDNBR_SLNO            VARCHAR2(5) NULL,
	BULD_NM               VARCHAR2(60) NULL,
	DETAIL_BULD_NM        VARCHAR2(60) NULL,
	ZIP                   VARCHAR2(6) NOT NULL,
	FRST_REGIST_PNTTM     DATE NULL,
	FRST_REGISTER_ID      VARCHAR2(20) NULL,
	LAST_UPDT_PNTTM       DATE NULL,
	LAST_UPDUSR_ID        VARCHAR2(20) NULL,
CONSTRAINT  RDNMADR_ZIP_PK PRIMARY KEY (SN)
);
CREATE TABLE NCRD
(
	NCRD_ID               CHAR(20)  NOT NULL ,
	NCRD_TRGTER_ID        VARCHAR2(20)  NULL ,
	NM                    VARCHAR2(50)  NOT NULL ,
	TELNO                 VARCHAR2(20)  NULL ,
	NATION_NO             VARCHAR2(10)  NULL ,
	AREA_NO               VARCHAR2(4)  NULL ,
	MIDDLE_TELNO          VARCHAR2(4)  NULL ,
	END_TELNO             VARCHAR2(4)  NULL ,
	MBTLNUM               VARCHAR2(20)  NULL ,
	IDNTFC_NO             VARCHAR2(10)  NULL ,
	MIDDLE_MBTLNUM        VARCHAR2(4)  NULL ,
	END_MBTLNUM           VARCHAR2(4)  NULL ,
	EMAIL_ADRES           VARCHAR2(50)  NULL ,
	CMPNY_NM              VARCHAR2(60)  NULL ,
	DEPT_NM               VARCHAR2(60)  NULL ,
	ADRES                 VARCHAR2(100)  NULL ,
	DETAIL_ADRES          VARCHAR2(100)  NULL ,
	OFCPS_NM              VARCHAR2(60)  NULL ,
	CLSF_NM               VARCHAR2(60)  NULL ,
	EXTRL_USER_AT         CHAR(1)  NULL ,
	OTHBC_AT              CHAR(1)  NOT NULL ,
	RM                    VARCHAR2(2500)  NULL ,
	FRST_REGIST_PNTTM     DATE  NOT NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
CONSTRAINT  NCRD_PK PRIMARY KEY (NCRD_ID)
);

CREATE TABLE NCRD_USER
(
	NCRD_ID               CHAR(20)  NOT NULL ,
	REGIST_SE_CODE        CHAR(6)  NOT NULL ,
	USE_AT                CHAR(1)  NOT NULL ,
	CREAT_DT              DATE  NOT NULL ,
	EMPLYR_ID             VARCHAR2(20)  NOT NULL ,
CONSTRAINT  NCRD_USER_PK PRIMARY KEY (NCRD_ID,EMPLYR_ID),
CONSTRAINT  NCRD_USER_FK1 FOREIGN KEY (NCRD_ID) REFERENCES NCRD(NCRD_ID)
);
CREATE TABLE WEB_LOG_SUMMARY
(
	OCCRRNC_DE            CHAR(20)  NOT NULL ,
	URL                   VARCHAR2(100)  NOT NULL ,
	RDCNT                 NUMBER(10)  NULL ,
CONSTRAINT  WEB_LOG_SUMMARY_PK PRIMARY KEY (OCCRRNC_DE,URL)
);

CREATE TABLE LOGIN_LOG
(
	LOG_ID                CHAR(20)  NOT NULL ,
	CONECT_ID             VARCHAR2(20)  NULL ,
	CONECT_IP             VARCHAR2(23)  NULL ,
	CONECT_MTHD           CHAR(4)  NULL ,
	ERROR_OCCRRNC_AT      CHAR(1)  NULL ,
	ERROR_CODE            CHAR(3)  NULL ,
	CREAT_DT              DATE  NULL ,
CONSTRAINT  COMTNLOGINLOG_PK PRIMARY KEY (LOG_ID)
);

CREATE TABLE WEB_LOG
(
	REQUST_ID             VARCHAR2(20)  NOT NULL ,
	OCCRRNC_DE            CHAR(20)  NULL ,
	URL                   VARCHAR2(100)  NULL ,
	RQESTER_ID            VARCHAR2(20)  NULL ,
	RQESTER_IP            VARCHAR2(23)  NULL ,
CONSTRAINT  WEB_LOG_PK PRIMARY KEY (REQUST_ID)
);

CREATE TABLE EVENT
(
	EVENT_ID              CHAR(20)  NOT NULL ,
	BSNS_YEAR             CHAR(4)  NULL ,
	BSNS_CODE             VARCHAR2(2)  NULL ,
	EVENT_CN              VARCHAR2(1000)  NULL ,
	EVENT_SVC_BGNDE       CHAR(20)  NULL ,
	SVC_USE_NMPR_CO       NUMBER(10)  NULL ,
	CHARGER_NM            VARCHAR2(50)  NULL ,
	PRPARETG_CN           VARCHAR2(2500)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	EVENT_SVC_ENDDE       CHAR(20)  NULL ,
	EVENT_TY_CODE         CHAR(1)  NULL ,
	EVENT_CONFM_AT        CHAR(1)  NULL ,
	EVENT_CONFM_DE        CHAR(20)  NULL ,
CONSTRAINT  EVENT_PK PRIMARY KEY (EVENT_ID)
);

CREATE TABLE EXTRL_HR
(
	EVENT_ID              CHAR(20)  NOT NULL ,
	EXTRL_HR_ID           CHAR(20)  NOT NULL ,
	SEXDSTN_CODE          CHAR(1)  NULL ,
	EXTRL_HR_NM           VARCHAR2(60)  NULL ,
	OCCP_TY_CODE          CHAR(1)  NULL ,
	PSITN_INSTT_NM        VARCHAR2(100)  NULL ,
	BRTHDY                CHAR(20)  NULL ,
	AREA_NO               VARCHAR2(4)  NULL ,
	MIDDLE_TELNO          VARCHAR2(4)  NULL ,
	END_TELNO             VARCHAR2(4)  NULL ,
	EMAIL_ADRES           VARCHAR2(50)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
CONSTRAINT  EXTRL_HR_PK PRIMARY KEY (EVENT_ID,EXTRL_HR_ID),
CONSTRAINT  EXTRL_HR_FK1 FOREIGN KEY (EVENT_ID) REFERENCES EVENT(EVENT_ID)
);
CREATE TABLE ADBK_MANAGE
(
	ADBK_ID               CHAR(20)  NOT NULL ,
	ADBK_NM               VARCHAR2(50)  NOT NULL ,
	OTHBC_SCOPE           VARCHAR2(20)  NOT NULL ,
	USE_AT                CHAR(1)  NOT NULL ,
	WRTER_ID              VARCHAR2(20)  NULL ,
	TRGET_ORGNZT_ID       CHAR(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NOT NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NOT NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
CONSTRAINT  ADBK_MANAGE_PK PRIMARY KEY (ADBK_ID)
);
CREATE TABLE ADBK
(
	EMPLYR_ID             VARCHAR2(20) NULL ,
	NCRD_ID               CHAR(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	ADBK_CONSTNT_ID       CHAR(20)  NOT NULL ,
	NM                    VARCHAR2(50)  NULL ,
	EMAIL_ADRES           VARCHAR2(50)  NULL ,
	MBTLNUM               VARCHAR2(20)  NULL ,
	FXNUM                 VARCHAR2(20)  NULL ,
	OFFM_TELNO            VARCHAR2(20)  NULL ,
	HOUSE_TELNO           VARCHAR2(20)  NULL ,
	ADBK_ID               CHAR(20)  NOT NULL ,
CONSTRAINT  ADBK_PK PRIMARY KEY (ADBK_CONSTNT_ID,ADBK_ID),
CONSTRAINT  ADBK_FK1 FOREIGN KEY (ADBK_ID) REFERENCES ADBK_MANAGE(ADBK_ID) ON DELETE CASCADE
);


CREATE TABLE ADMINIST_WORD
(
	ADMINIST_WORD_ID      CHAR(20)  NOT NULL ,
	ADMINIST_WORD_NM      VARCHAR2(255)  NULL ,
	ADMINIST_WORD_ENG_NM  VARCHAR2(255)  NULL ,
	ADMINIST_WORD_ABRV_NM  VARCHAR2(255)  NULL ,
	THEMA_RELM            VARCHAR2(255)  NULL ,
	WORD_SE               VARCHAR2(255)  NULL ,
	RELATE_STD_WORD       VARCHAR2(255)  NULL ,
	ADMINIST_WORD_DFN     VARCHAR2(2500)  NULL ,
	ADMINIST_WORD_DC      VARCHAR2(4000)  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
CONSTRAINT  ADMINIST_WORD_PK PRIMARY KEY (ADMINIST_WORD_ID)
);

CREATE TABLE ONLINE_MANUAL
(
	ONLINE_MNL_ID         CHAR(20)  NOT NULL ,
	ONLINE_MNL_SE_CODE    CHAR(3)  NULL ,
	ONLINE_MNL_DFN        CLOB  NULL ,
	ONLINE_MNL_DC         CLOB  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	ONLINE_MNL_NM         VARCHAR2(255)  NULL ,
CONSTRAINT  ONLINE_MANUAL_PK PRIMARY KEY (ONLINE_MNL_ID)
);
CREATE TABLE USER_SUMMARY
(
	OCCRRNC_DE            CHAR(20)  NOT NULL ,
	STATS_SE              VARCHAR2(10)  NOT NULL ,
	DETAIL_STATS_SE       VARCHAR2(10)  NOT NULL ,
	USER_CO               NUMBER(10)  NULL ,
CONSTRAINT  USER_SUMMARY_PK PRIMARY KEY (OCCRRNC_DE,STATS_SE,DETAIL_STATS_SE)
);
CREATE TABLE MTG
(
	MTG_ID                CHAR(20)  NOT NULL ,
	MTG_NM                VARCHAR2(255)  NULL ,
	MTG_MTR_CN            VARCHAR2(1000)  NULL ,
	MTG_SN                NUMBER(10)  NULL ,
	MTG_CO                NUMBER(5)  NULL ,
	MTG_DE                CHAR(20)  NULL ,
	MTG_PLACE             VARCHAR2(255)  NULL ,
	MTG_BEGIN_TM          VARCHAR2(14)  NULL ,
	MTG_END_TM            VARCHAR2(14)  NULL ,
	CLSDR_MTG_AT          CHAR(1)  NULL ,
	READNG_BGNDE          CHAR(20)  NULL ,
	READNG_AT             CHAR(1)  NULL ,
	MTG_RESULT_CN         VARCHAR2(1000)  NULL ,
	MTG_RESULT_ENNC       CHAR(1)  NULL ,
	ETC_MATTER            VARCHAR2(1000)  NULL ,
	MNGT_DEPT_ID          VARCHAR2(20)  NULL ,
	MNAER_ID              VARCHAR2(20)  NULL ,
	MNAER_DEPT_ID         VARCHAR2(20)  NULL ,
	MTG_AT                CHAR(1)  NULL ,
	NONATDRN_CO           NUMBER(10)  NULL ,
	ATDRN_CO              NUMBER(10)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
CONSTRAINT  MTG_PK PRIMARY KEY (MTG_ID)
);

CREATE TABLE REPRT_STATS
(
	REPRT_ID              CHAR(6)  NOT NULL ,
	REPRT_NM              VARCHAR2(20)  NOT NULL ,
	REPRT_STTUS           CHAR(2)  NOT NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NOT NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	REPRT_TY              CHAR(2)  NULL ,
CONSTRAINT  REPRT_STATS_PK PRIMARY KEY (REPRT_ID)
);

CREATE TABLE SMS
(
	SMS_ID                CHAR(20)  NOT NULL ,
	TRNSMIS_TELNO         VARCHAR2(12)  NOT NULL ,
	TRNSMIS_CN            VARCHAR2(80)  NOT NULL ,
	FRST_REGIST_PNTTM     DATE  NOT NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NOT NULL ,
CONSTRAINT  SMS_PK PRIMARY KEY (SMS_ID)
);

CREATE TABLE SMS_RECPTN
(
	SMS_ID                CHAR(20)  NOT NULL ,
	RECPTN_TELNO          VARCHAR2(12)  NOT NULL ,
	RESULT_CODE           VARCHAR2(4)  NULL ,
	RESULT_MSSAGE         VARCHAR2(4000)  NULL ,
CONSTRAINT  SMS_RECPTN_PK PRIMARY KEY (SMS_ID,RECPTN_TELNO),
CONSTRAINT  SMS_RECPTN_FK1 FOREIGN KEY (SMS_ID) REFERENCES SMS(SMS_ID)
);

CREATE TABLE CPYRHT
(
	CPYRHT_ID             CHAR(20)  NOT NULL ,
	CPYRHT_PRTC_POLICY_CN  VARCHAR2(2500)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
CONSTRAINT  CPYRHT_PK PRIMARY KEY (CPYRHT_ID)
);
CREATE TABLE DIARY
(
	SCHDUL_ID             CHAR(20)  NOT NULL ,
	DIARY_ID              CHAR(20)  NOT NULL ,
	DIARY_PROGRSRT        NUMBER(3)  NULL ,
	DIARY_NM              VARCHAR2(255)  NULL ,
	DRCT_MATTER           VARCHAR2(2500)  NULL ,
	PARTCLR_MATTER        VARCHAR2(2500)  NULL ,
	ATCH_FILE_ID          CHAR(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
CONSTRAINT  DIARY_PK PRIMARY KEY (SCHDUL_ID,DIARY_ID),
CONSTRAINT  DIARY_FK1 FOREIGN KEY (SCHDUL_ID) REFERENCES SCHDUL(SCHDUL_ID)
);
CREATE TABLE ONLINE_POLL_MANAGE
(
	POLL_ID               CHAR(20)  NOT NULL ,
	POLL_NM               VARCHAR2(255)  NULL ,
	POLL_BGNDE            CHAR(10)  NULL ,
	POLL_ENDDE            CHAR(10)  NULL ,
	POLL_KND              CHAR(3)  NULL ,
	POLL_DSUSE_ENNC       CHAR(1)  NULL ,
	POLL_ATMC_DSUSE_ENNC  CHAR(1)  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
CONSTRAINT  POLL_MANAGE_PK PRIMARY KEY (POLL_ID)
);
CREATE TABLE ONLINE_POLL_IEM
(
	POLL_IEM_NM           VARCHAR2(255)  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	POLL_IEM_ID           CHAR(20)  NOT NULL ,
	POLL_ID               CHAR(20)  NOT NULL ,
CONSTRAINT  POLL_IEM_PK PRIMARY KEY (POLL_ID,POLL_IEM_ID),
CONSTRAINT  POLL_IEM_FK1 FOREIGN KEY (POLL_ID) REFERENCES ONLINE_POLL_MANAGE(POLL_ID)
);
CREATE TABLE ONLINE_POLL_RESULT
(
	POLL_RESULT_ID        CHAR(20)  NOT NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	POLL_IEM_ID           CHAR(20)  NOT NULL ,
	POLL_ID               CHAR(20)  NOT NULL ,
CONSTRAINT  ONLINE_POLL_RESULT_PK PRIMARY KEY (POLL_RESULT_ID,POLL_IEM_ID,POLL_ID),
CONSTRAINT  ONLINE_POLL_RESULT_FK1 FOREIGN KEY (POLL_ID,POLL_IEM_ID) REFERENCES ONLINE_POLL_IEM(POLL_ID,POLL_IEM_ID)
);

CREATE TABLE WORD_DICARY
(
	WORD_ID               CHAR(20)  NOT NULL ,
	WORD_NM               VARCHAR2(255)  NULL ,
	ENG_NM                VARCHAR2(60)  NULL ,
	WORD_DC               VARCHAR2(4000)  NULL ,
	SYNONM                VARCHAR2(100)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
CONSTRAINT  WORD_DICARY_PK PRIMARY KEY (WORD_ID)
);
CREATE TABLE CNTC_SERVICE
(
	INSTT_ID              VARCHAR2(20)  NOT NULL ,
	SYS_ID                VARCHAR2(20)  NOT NULL ,
	SVC_ID                VARCHAR2(20)  NOT NULL ,
	SVC_NM                VARCHAR2(255)  NULL ,
	REQUST_MSSAGE_ID      VARCHAR2(20)  NULL ,
	RSPNS_MSSAGE_ID       VARCHAR2(20)  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	USE_AT                CHAR(1)  NULL ,
CONSTRAINT  CNTC_SERVICE_PK PRIMARY KEY (INSTT_ID,SYS_ID,SVC_ID)
);
CREATE TABLE HPCM
(
	HPCM_ID               CHAR(20)  NOT NULL ,
	HPCM_SE_CODE          CHAR(1)  NULL ,
	HPCM_DFN              VARCHAR2(1000)  NULL ,
	HPCM_DC               VARCHAR2(2500)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
CONSTRAINT  HPCM_PK PRIMARY KEY (HPCM_ID)
);
CREATE TABLE NEWS
(
	NEWS_ID               CHAR(20)  NOT NULL ,
	NEWS_SJ               VARCHAR2(100)  NULL ,
	NEWS_CN               VARCHAR2(2500)  NULL ,
	NEWS_ORIGIN           VARCHAR2(250)  NULL ,
	NTCE_AT               CHAR(1)  NULL ,
	FRST_REGIST_PNTTM     DATE  NOT NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NOT NULL ,
	LAST_UPDT_PNTTM       DATE  NOT NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NOT NULL ,
	NTCE_DE               CHAR(20)  NULL ,
	ATCH_FILE_ID          CHAR(20)  NULL ,
CONSTRAINT  NEWS_PK PRIMARY KEY (NEWS_ID),
CONSTRAINT  NEWS_FK1 FOREIGN KEY (ATCH_FILE_ID) REFERENCES ATCH_FILE(ATCH_FILE_ID) ON DELETE CASCADE
);


CREATE TABLE CNSLT_LIST
(
	CNSLT_ID              CHAR(20)  NOT NULL ,
	CNSLT_SJ              VARCHAR2(255)  NULL ,
	OTHBC_AT              CHAR(1)  NULL ,
	EMAIL_ADRES           VARCHAR2(50)  NULL ,
	CNSLT_CN              VARCHAR2(2500)  NULL ,
	MANAGT_CN             VARCHAR2(2500)  NULL ,
	MANAGT_DE             CHAR(20)  NULL ,
	RDCNT                 NUMBER(10)  NULL ,
	ATCH_FILE_ID          CHAR(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	AREA_NO               VARCHAR2(4)  NULL ,
	MIDDLE_TELNO          VARCHAR2(4)  NULL ,
	END_TELNO             VARCHAR2(4)  NULL ,
	FRST_MBTLNUM          VARCHAR2(4)  NULL ,
	MIDDLE_MBTLNUM        VARCHAR2(4)  NULL ,
	END_MBTLNUM           VARCHAR2(4)  NULL ,
	WRITNG_DE             CHAR(20)  NULL ,
	WRTER_NM              VARCHAR2(20)  NULL ,
	EMAIL_ANSWER_AT       CHAR(1)  NULL ,
	QNA_PROCESS_STTUS_CODE  CHAR(1)  NULL ,
	WRITNG_PASSWORD       VARCHAR2(20)  NULL ,
CONSTRAINT  CNSLT_LIST_PK PRIMARY KEY (CNSLT_ID)
);
CREATE TABLE SITE_MAP
(
	MAPNG_CREAT_ID        VARCHAR2(30)  NOT NULL ,
	CREATR_ID             VARCHAR2(20)  NOT NULL ,
	MAPNG_FILE_NM         VARCHAR2(60)  NOT NULL ,
	MAPNG_FILE_PATH       VARCHAR2(100)  NOT NULL ,
CONSTRAINT  SITE_MAP_PK PRIMARY KEY (MAPNG_CREAT_ID)
);

CREATE TABLE NTFC
(
	NTCN_NO               NUMBER(20)  NOT NULL ,
	NTCN_SJ               VARCHAR2(60)  NOT NULL ,
	NTCN_CN               VARCHAR2(100)  NOT NULL ,
	NTCN_TM               VARCHAR2(14)  NOT NULL ,
	BH_NTCN_INTRVL        VARCHAR2(20)  NOT NULL ,
	FRST_REGIST_PNTTM     DATE  NOT NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NOT NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
CONSTRAINT  COMTNNTFCINFO_PK PRIMARY KEY (NTCN_NO)
);

CREATE TABLE CNTC_SYSTEM
(
	INSTT_ID              VARCHAR2(20)  NOT NULL ,
	SYS_ID                VARCHAR2(20)  NOT NULL ,
	SYS_NM                VARCHAR2(255)  NULL ,
	SYS_IP                VARCHAR2(23)  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	USE_AT                CHAR(1)  NULL ,
CONSTRAINT  CNTC_SYSTEM_PK PRIMARY KEY (INSTT_ID,SYS_ID)
);

CREATE TABLE ANSWER
(
	NTT_ID                NUMBER(20)  NOT NULL ,
	BBS_ID                CHAR(20)  NOT NULL ,
	WRTER_ID              VARCHAR2(20)  NULL ,
	ANSWER                VARCHAR2(200)  NULL ,
	USE_AT                CHAR(1)  NOT NULL ,
	WRTER_NM              VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NOT NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NOT NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	ANSWER_NO             NUMBER(20)  NOT NULL ,
CONSTRAINT  ANSWER_PK PRIMARY KEY (NTT_ID,BBS_ID,ANSWER_NO),
CONSTRAINT  ANSWER_FK1 FOREIGN KEY (BBS_ID) REFERENCES BBS_MASTER_OPTN(BBS_ID)
);
CREATE TABLE TRSMRCV_LOG
(
	REQUST_ID             VARCHAR2(20)  NOT NULL ,
	OCCRRNC_DE            CHAR(20)  NULL ,
	TRSMRCV_SE_CODE       CHAR(3)  NULL ,
	CNTC_ID               CHAR(8)  NULL ,
	PROVD_INSTT_ID        CHAR(8)  NULL ,
	PROVD_SYS_ID          CHAR(8)  NULL ,
	PROVD_SVC_ID          CHAR(8)  NULL ,
	REQUST_INSTT_ID       CHAR(8)  NULL ,
	REQUST_SYS_ID         CHAR(8)  NULL ,
	REQUST_TRNSMIT_TM     VARCHAR2(14)  NULL ,
	REQUST_RECPTN_TM      VARCHAR2(14)  NULL ,
	RSPNS_TRNSMIT_TM      VARCHAR2(14)  NULL ,
	RSPNS_RECPTN_TM       VARCHAR2(14)  NULL ,
	RESULT_CODE           VARCHAR2(4)  NULL ,
	RESULT_MSSAGE         VARCHAR2(4000)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	RQESTER_ID            VARCHAR2(20)  NULL ,
CONSTRAINT  TRSMRCV_LOG_PK PRIMARY KEY (REQUST_ID)
);

CREATE TABLE DAMCALRES
(
	ORGNZT_ID             CHAR(20)  NULL ,
	EXPERT_ID             CHAR(20)  NULL ,
	KNWLDG_TY_CODE        VARCHAR2(3)  NULL ,
	EMPLYR_ID             VARCHAR2(20)  NULL ,
	KNWLDG_NM             VARCHAR2(60)  NULL ,
	KNWLDG_CN             VARCHAR2(2500)  NULL ,
	ATCH_FILE_ID          CHAR(20)  NULL ,
	PARNTS_KNWLDG_ID      CHAR(20)  NULL ,
	ANSWER_DP             NUMBER(20)  NULL ,
	ANSWER_ORDR           NUMBER(20)  NULL ,
	ANSWER_GROUP_NO       NUMBER(20)  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	KNWLDG_ID             CHAR(20)  NOT NULL ,
CONSTRAINT  DAMCALRES_PK PRIMARY KEY (KNWLDG_ID)
);
CREATE TABLE BACKUP_RESULT
(
	BACKUP_RESULT_ID      VARCHAR2(20)  NOT NULL ,
	BACKUP_OPERT_ID       VARCHAR2(20)  NOT NULL ,
	BACKUP_FILE           VARCHAR2(255)  NULL ,
	STTUS                 VARCHAR2(2)  NULL ,
	ERROR_INFO            VARCHAR2(2000)  NULL ,
	EXECUT_BEGIN_TM       VARCHAR2(14)  NULL ,
	EXECUT_END_TM         VARCHAR2(14)  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NOT NULL ,
CONSTRAINT  BACKUP_RESULT_PK PRIMARY KEY (BACKUP_RESULT_ID)
);

CREATE TABLE COMTHTRSMRCVMNTRNG_LOG 
(
	LOG_ID                CHAR(20)  NOT NULL ,
	CNTC_ID               CHAR(8)  NOT NULL ,
	TEST_CLASS_NM         VARCHAR2(255)  NULL ,
	MNGR_NM               VARCHAR2(60)  NULL ,
	MNGR_EMAIL_ADRES      VARCHAR2(50)  NULL ,
	MNTRNG_STTUS          CHAR(2)  NULL ,
	LOG_INFO              VARCHAR2(2000)  NULL ,
	CREAT_DT              DATE  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NOT NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NOT NULL ,
CONSTRAINT  COMTHTRSMRCVMNTRNG_LOG_PK PRIMARY KEY (LOG_ID)
);
CREATE TABLE SCRAP
(
	SCRAP_ID              CHAR(20)  NOT NULL ,
	NTT_ID                NUMBER(20)  NOT NULL ,
	BBS_ID                CHAR(20)  NOT NULL ,
	SCRAP_NM              VARCHAR2(100)  NOT NULL ,
	USE_AT                CHAR(1)  NOT NULL ,
	FRST_REGIST_PNTTM     DATE  NOT NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NOT NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
CONSTRAINT  SCRAP_PK PRIMARY KEY (SCRAP_ID)
);


CREATE TABLE CNTC_INSTT
(
	INSTT_ID              VARCHAR2(20)  NOT NULL ,
	INSTT_NM              VARCHAR2(100)  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	USE_AT                CHAR(1)  NULL ,
CONSTRAINT  CNTC_INSTT_PK PRIMARY KEY (INSTT_ID)
);
CREATE TABLE HIST
(
	HIST_ID               CHAR(20)  NOT NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NOT NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	HIST_SE_CODE          CHAR(6)  NOT NULL ,
	HIST_CN               VARCHAR2(2500)  NOT NULL ,
	SYS_NM                VARCHAR2(255)  NOT NULL ,
	ATCH_FILE_ID          CHAR(20)  NULL ,
CONSTRAINT  HIST_PK PRIMARY KEY (HIST_ID)
);

CREATE TABLE HTTP_MON
(
	SYS_ID                VARCHAR2(20)  NOT NULL ,
	SITE_URL              VARCHAR2(100)  NULL ,
	WEBSVC_KND            VARCHAR2(10)  NULL ,
	HTTP_STTUS_CODE       VARCHAR2(3)  NULL ,
	CREAT_DT              DATE  NULL ,
	MNGR_NM               VARCHAR2(60)  NULL ,
	MNGR_EMAIL_ADRES      VARCHAR2(50)  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
CONSTRAINT  HTTP_MON_PK PRIMARY KEY (SYS_ID)
);

CREATE TABLE HTTP_MON_LOG
(
	SYS_ID                VARCHAR2(20)  NOT NULL ,
	SITE_URL              VARCHAR2(100)  NULL ,
	WEBSVC_KND            VARCHAR2(10)  NULL ,
	HTTP_STTUS_CODE       VARCHAR2(3)  NULL ,
	CREAT_DT              DATE  NULL ,
	LOG_INFO              VARCHAR2(2000)  NULL ,
	MNGR_NM               VARCHAR2(60)  NULL ,
	MNGR_EMAIL_ADRES      VARCHAR2(50)  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	LOG_ID                CHAR(20)  NOT NULL ,
CONSTRAINT  HTTP_MON_LOG_PK PRIMARY KEY (SYS_ID,LOG_ID),
CONSTRAINT  HTTP_MON_LOG_FK2 FOREIGN KEY (SYS_ID) REFERENCES HTTP_MON(SYS_ID)
);


CREATE TABLE DB_LOG
(
	DATA_SOURC_NM         VARCHAR2(60)  NOT NULL ,
	SERVER_NM             VARCHAR2(60)  NULL ,
	DBMS_KND              VARCHAR2(2)  NULL ,
	CECK_SQL              VARCHAR2(250)  NULL ,
	MNGR_NM               VARCHAR2(60)  NULL ,
	MNGR_EMAIL_ADRES      VARCHAR2(50)  NULL ,
	MNTRNG_STTUS          CHAR(2)  NULL ,
	LOG_INFO              VARCHAR2(2000)  NULL ,
	CREAT_DT              DATE  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NOT NULL ,
	LAST_UPDT_PNTTM       DATE  NOT NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LOG_ID                CHAR(20)  NOT NULL ,
CONSTRAINT  DB_LOG_PK PRIMARY KEY (LOG_ID)
);
CREATE TABLE CONFM_HISTORY
(
	CONFM_NO              NUMBER(8)  NOT NULL ,
	CONFM_RQESTER_ID      VARCHAR2(20)  NOT NULL ,
	CONFMER_ID            VARCHAR2(20)  NULL ,
	CONFM_DE              CHAR(20)  NULL ,
	CONFM_TY_CODE         CHAR(4)  NOT NULL ,
	CONFM_STTUS_CODE      CHAR(4)  NOT NULL ,
	OPERT_TY_CODE         CHAR(4)  NULL ,
	OPERT_ID              VARCHAR2(20)  NULL ,
	TRGET_JOB_TY_CODE     CHAR(3)  NULL ,
	TRGET_JOB_ID          CHAR(20)  NULL ,
CONSTRAINT  CONFM_HISTORY_PK PRIMARY KEY (CONFM_NO)
);

CREATE TABLE DAMMAP_TEAM
(
	ORGNZT_ID             CHAR(20)  NOT NULL ,
	ORGNZT_NM             VARCHAR2(20)  NULL ,
	CL_DE                 CHAR(20)  NULL ,
	KNWLDG_URL            VARCHAR2(255)  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
CONSTRAINT  DAMMAP_TEAM_PK PRIMARY KEY (ORGNZT_ID)
);
CREATE TABLE INDVDL_PGE_CNTNTS
(
	CNTNTS_ID             VARCHAR2(20)  NOT NULL ,
	CNTNTS_NM             VARCHAR2(100)  NOT NULL ,
	CNTC_URL              VARCHAR2(255)  NOT NULL ,
	CNTNTS_USE_AT         CHAR(1)  NOT NULL ,
	CNTNTS_LINK_URL       VARCHAR2(1000)  NULL ,
	CNTNTS_DC             VARCHAR2(250)  NULL ,
CONSTRAINT  INDVDL_PGE_CNTNTS_PK PRIMARY KEY (CNTNTS_ID)
);

CREATE TABLE INDVDL_PGE_ESTBS
(
	EMPLYR_ID             VARCHAR2(20)  NOT NULL ,
	UPEND_IMAGE           VARCHAR2(1024)  NULL ,
	TITLEBAR_COLOR        CHAR(7)  NULL ,
	ALGN_MTHD             CHAR(1)  NULL ,
	ALGN_CO               NUMBER(10)  NULL ,
CONSTRAINT  INDVDL_PGE_ESTBS_PK PRIMARY KEY (EMPLYR_ID)
);
CREATE TABLE CNTNTS_LIST
(
	CNTNTS_ID             VARCHAR2(20)  NOT NULL ,
	EMPLYR_ID             VARCHAR2(20)  NOT NULL ,
CONSTRAINT  CNTNTS_LIST_PK PRIMARY KEY (CNTNTS_ID,EMPLYR_ID),
CONSTRAINT  CNTNTS_LIST_FK1 FOREIGN KEY (CNTNTS_ID) REFERENCES INDVDL_PGE_CNTNTS(CNTNTS_ID),
CONSTRAINT  CNTNTS_LIST_FK2 FOREIGN KEY (EMPLYR_ID) REFERENCES INDVDL_PGE_ESTBS(EMPLYR_ID)
);

CREATE TABLE CNTC_MESSAGE
(
	CNTC_MSSAGE_ID        VARCHAR2(20)  NOT NULL ,
	CNTC_MSSAGE_NM        VARCHAR2(100)  NULL ,
	UPPER_CNTC_MSSAGE_ID  VARCHAR2(20)  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	USE_AT                CHAR(1)  NULL ,
CONSTRAINT  CNTC_MESSAGE_PK PRIMARY KEY (CNTC_MSSAGE_ID)
);
CREATE TABLE CNTC_MESSAGE_ITEM
(
	CNTC_MSSAGE_ID        VARCHAR2(20)  NOT NULL ,
	IEM_ID                VARCHAR2(20)  NOT NULL ,
	IEM_NM                VARCHAR2(100)  NULL ,
	IEM_TY                VARCHAR2(50)  NULL ,
	IEM_LT                NUMBER(8)  NULL ,
	USE_AT                CHAR(1)  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
CONSTRAINT  CNTC_MESSAGE_ITEM_PK PRIMARY KEY (CNTC_MSSAGE_ID,IEM_ID),
CONSTRAINT  CNTC_MESSAGE_ITEM_FK1 FOREIGN KEY (CNTC_MSSAGE_ID) REFERENCES COMTNCNTCMESSAGE(CNTC_MSSAGE_ID)
);

CREATE TABLE MENU_MANAGE_RESULT
(
	MENU_ID               NUMBER(20)  NOT NULL ,
	EMPLYR_ID             VARCHAR2(20)  NOT NULL ,
	MENU_NM               VARCHAR2(60)  NOT NULL ,
	PROGRM_STRE_PATH      VARCHAR2(100)  NOT NULL ,
CONSTRAINT  MENU_MANAGE_RESULT_PK PRIMARY KEY (MENU_ID,EMPLYR_ID)
);
CREATE TABLE SYSTEM_CNTC
(
	CNTC_ID               CHAR(8)  NOT NULL ,
	CNTC_NM               VARCHAR2(100)  NULL ,
	PROVD_INSTT_ID        CHAR(8)  NULL ,
	PROVD_SYS_ID          CHAR(8)  NULL ,
	PROVD_SVC_ID          CHAR(8)  NULL ,
	REQUST_INSTT_ID       CHAR(8)  NULL ,
	REQUST_SYS_ID         CHAR(8)  NULL ,
	CONFM_AT              CHAR(1)  NULL ,
	USE_AT                CHAR(1)  NULL ,
	VALID_BGNDE           CHAR(20)  NULL ,
	VALID_ENDDE           CHAR(20)  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	CNTC_TY               VARCHAR2(60)  NULL ,
CONSTRAINT  SYSTEM_CNTC_PK PRIMARY KEY (CNTC_ID)
);

CREATE TABLE BNDT_MANAGE
(
	BNDT_ID               VARCHAR2(20)  NOT NULL ,
	BNDT_DE               CHAR(8)  NOT NULL ,
	RM                    VARCHAR2(2500)  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
CONSTRAINT  BNDT_MANAGE_PK PRIMARY KEY (BNDT_ID,BNDT_DE)
);

CREATE TABLE BNDT_CECK_MANAGE
(
	BNDT_CECK_SE          CHAR(2)  NOT NULL ,
	BNDT_CECK_CODE        VARCHAR2(10)  NOT NULL ,
	BNDT_CECK_CODE_NM     VARCHAR2(255)  NOT NULL ,
	USE_AT                CHAR(1)  NOT NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
CONSTRAINT  BNDT_CECK_MANAGE_PK PRIMARY KEY (BNDT_CECK_CODE,BNDT_CECK_SE)
);

CREATE TABLE BNDT_DIARY
(
	BNDT_ID               VARCHAR2(20)  NOT NULL ,
	BNDT_DE               CHAR(8)  NOT NULL ,
	BNDT_CECK_SE          CHAR(2)  NOT NULL ,
	BNDT_CECK_CODE        VARCHAR2(10)  NOT NULL ,
	CHCK_STTUS            VARCHAR2(1000)  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
CONSTRAINT  BNDT_DIARY_PK PRIMARY KEY (BNDT_ID,BNDT_DE,BNDT_CECK_SE,BNDT_CECK_CODE),
CONSTRAINT  BNDT_DIARY_FK2 FOREIGN KEY (BNDT_ID,BNDT_DE) REFERENCES BNDT_MANAGE(BNDT_ID,BNDT_DE),
CONSTRAINT  BNDT_DIARY_FK1 FOREIGN KEY (BNDT_CECK_CODE,BNDT_CECK_SE) REFERENCES BNDT_CECK_MANAGE(BNDT_CECK_CODE,BNDT_CECK_SE)
);

CREATE TABLE BATCH_RESULT
(
	BATCH_RESULT_ID       VARCHAR2(20)  NOT NULL ,
	BATCH_SCHDUL_ID       VARCHAR2(20)  NOT NULL ,
	BATCH_OPERT_ID        VARCHAR2(20)  NOT NULL ,
	PARAMTR               VARCHAR2(250)  NULL ,
	STTUS                 VARCHAR2(2)  NULL ,
	ERROR_INFO            VARCHAR2(2000)  NULL ,
	EXECUT_BEGIN_TM       VARCHAR2(14)  NULL ,
	EXECUT_END_TM         VARCHAR2(14)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NOT NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
CONSTRAINT  BATCH_RESULT_PK PRIMARY KEY (BATCH_RESULT_ID)
);

CREATE TABLE STSFDG
(
	STSFDG_NO             NUMBER(20)  NOT NULL ,
	NTT_ID                NUMBER(20)  NOT NULL ,
	BBS_ID                CHAR(20)  NOT NULL ,
	WRTER_ID              VARCHAR2(20)  NULL ,
	WRTER_NM              VARCHAR2(20)  NULL ,
	PASSWORD              VARCHAR2(200)  NULL ,
	STSFDG                NUMBER(1)  NOT NULL ,
	STSFDG_CN             VARCHAR2(200)  NULL ,
	USE_AT                CHAR(1)  NOT NULL ,
	FRST_REGIST_PNTTM     DATE  NOT NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NOT NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
CONSTRAINT  STSFDG_PK PRIMARY KEY (STSFDG_NO)
);
CREATE TABLE BATCH_OPERT
(
	BATCH_OPERT_ID        VARCHAR2(20)  NOT NULL ,
	BATCH_OPERT_NM        VARCHAR2(60)  NULL ,
	BATCH_PROGRM          VARCHAR2(255)  NULL ,
	PARAMTR               VARCHAR2(250)  NULL ,
	USE_AT                CHAR(1)  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NOT NULL ,
CONSTRAINT  BATCH_OPERT_PK PRIMARY KEY (BATCH_OPERT_ID)
);
CREATE TABLE FILE_SYS_MNTRNG
(
	FILE_SYS_ID           CHAR(20)  NOT NULL ,
	FILE_SYS_NM           VARCHAR2(60)  NOT NULL ,
	FILE_SYS_MANAGE_NM    VARCHAR2(255)  NOT NULL ,
	FILE_SYS_SIZE         NUMBER(8)  NOT NULL ,
	FILE_SYS_THRHLD       NUMBER(8)  NOT NULL ,
	FILE_SYS_USGQTY       NUMBER(8)  NULL ,
	MNGR_NM               VARCHAR2(60)  NULL ,
	MNGR_EMAIL_ADRES      VARCHAR2(50)  NULL ,
	MNTRNG_STTUS          CHAR(2)  NULL ,
	CREAT_DT              DATE  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
CONSTRAINT  FILE_SYS_MNTRNG_PK PRIMARY KEY (FILE_SYS_ID)
);

CREATE TABLE FILE_SYS_MNTRNG_LOG
(
	FILE_SYS_ID           CHAR(20)  NOT NULL ,
	FILE_SYS_NM           VARCHAR2(60)  NOT NULL ,
	FILE_SYS_MANAGE_NM    VARCHAR2(255)  NOT NULL ,
	FILE_SYS_SIZE         NUMBER(8)  NOT NULL ,
	FILE_SYS_THRHLD       NUMBER(8)  NOT NULL ,
	FILE_SYS_USGQTY       NUMBER(8)  NULL ,
	MNTRNG_STTUS          CHAR(2)  NULL ,
	LOG_INFO              VARCHAR2(2000)  NULL ,
	CREAT_DT              DATE  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	LOG_ID                CHAR(20)  NOT NULL ,
CONSTRAINT  FILE_SYS_MNTRNG_LOG_PK PRIMARY KEY (FILE_SYS_ID,LOG_ID),
CONSTRAINT  FILE_SYS_MNTRNG_LOG_FK2 FOREIGN KEY (FILE_SYS_ID) REFERENCES FILE_SYS_MNTRNG(FILE_SYS_ID)
);

CREATE TABLE BATCH_SCHDUL
(
	BATCH_SCHDUL_ID       VARCHAR2(20)  NOT NULL ,
	BATCH_OPERT_ID        VARCHAR2(20)  NOT NULL ,
	EXECUT_CYCLE          VARCHAR2(2)  NULL ,
	EXECUT_SCHDUL_DE      CHAR(20)  NULL ,
	EXECUT_SCHDUL_HOUR    CHAR(2)  NULL ,
	EXECUT_SCHDUL_MNT     CHAR(2)  NULL ,
	EXECUT_SCHDUL_SECND   CHAR(2)  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NOT NULL ,
CONSTRAINT  BATCH_SCHDUL_PK PRIMARY KEY (BATCH_SCHDUL_ID)
);

CREATE TABLE BATCH_SCHDUL_DFK
(
	BATCH_SCHDUL_ID       VARCHAR2(20)  NOT NULL ,
	EXECUT_SCHDUL_DFK_SE  CHAR(1)  NOT NULL ,
CONSTRAINT  BATCH_SCHDUL_DFK_PK PRIMARY KEY (BATCH_SCHDUL_ID,EXECUT_SCHDUL_DFK_SE),
CONSTRAINT  BATCH_SCHDUL_DFK_FK1 FOREIGN KEY (BATCH_SCHDUL_ID) REFERENCES BATCH_SCHDUL(BATCH_SCHDUL_ID)
);

CREATE TABLE CTSNN_MANAGE
(
	CTSNN_ID              VARCHAR2(20)  NOT NULL ,
	USER_ID               VARCHAR2(20)  NOT NULL ,
	CTSNN_CODE            CHAR(2)  NOT NULL ,
	REQST_DE              CHAR(20)  NOT NULL ,
	CTSNN_NM              VARCHAR2(255)  NOT NULL ,
	TRGTER_NM             VARCHAR2(20)  NOT NULL ,
	BRTHDY                CHAR(20)  NOT NULL ,
	OCCRRNC_DE            CHAR(20)  NOT NULL ,
	RELATE                CHAR(2)  NOT NULL ,
	RM                    VARCHAR2(2500)  NULL ,
	SANCTNER_ID           VARCHAR2(20)  NOT NULL ,
	CONFM_AT              CHAR(1)  NULL ,
	SANCTN_DT             DATE  NULL ,
	RETURN_RESN           VARCHAR2(1000)  NULL ,
	INFRML_SANCTN_ID      CHAR(20)  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
CONSTRAINT  CTSNN_MANAGE_PK PRIMARY KEY (CTSNN_ID)
);

CREATE TABLE ADMINIST_CODE_RECPTN_LOG
(
	OCCRRNC_DE            CHAR(20)  NOT NULL ,
	ADMINIST_ZONE_SE      CHAR(1)  NOT NULL ,
	ADMINIST_ZONE_CODE    VARCHAR2(10)  NOT NULL ,
	OPERT_SN              NUMBER(10)  NOT NULL ,
	CHANGE_SE_CODE        VARCHAR2(2)  NULL ,
	PROCESS_SE            VARCHAR2(2)  NULL ,
	ADMINIST_ZONE_NM      VARCHAR2(60)  NULL ,
	LOWEST_ADMINIST_ZONE_NM  VARCHAR2(60)  NULL ,
	CTPRVN_CODE           VARCHAR2(2)  NULL ,
	SIGNGU_CODE           VARCHAR2(3)  NULL ,
	EMD_CODE              VARCHAR2(3)  NULL ,
	LI_CODE               VARCHAR2(2)  NULL ,
	CREAT_DE              CHAR(20)  NULL ,
	ABL_DE                CHAR(20)  NULL ,
	ABL_ENNC              CHAR(1)  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
CONSTRAINT  ADMINIST_CODE_RECPTN_LOG_PK PRIMARY KEY (OCCRRNC_DE,ADMINIST_ZONE_SE,ADMINIST_ZONE_CODE,OPERT_SN)
);

CREATE TABLE TROBL
(
	TROBL_ID              CHAR(20)  NOT NULL ,
	TROBL_NM              VARCHAR2(60)  NULL ,
	TROBL_KND             CHAR(2)  NULL ,
	TROBL_DC              VARCHAR2(2000)  NULL ,
	TROBL_OCCRRNC_TIME    VARCHAR2(14)  NULL ,
	TROBL_RQESTER_NM      VARCHAR2(60)  NULL ,
	TROBL_REQUST_TIME     VARCHAR2(14)  NULL ,
	TROBL_PROCESS_RESULT  VARCHAR2(2000)  NULL ,
	TROBL_OPETR_NM        VARCHAR2(60)  NULL ,
	TROBL_PROCESS_TIME    VARCHAR2(14)  NULL ,
	PROCESS_STTUS         CHAR(1)  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
CONSTRAINT  TROBL_PK PRIMARY KEY (TROBL_ID)
);

CREATE TABLE COMTNDAMKNOIFM
(
	KNWLDG_ID             CHAR(20)  NOT NULL ,
	KNWLDG_TY_CODE        VARCHAR2(3)  NULL ,
	ORGNZT_ID             CHAR(20)  NULL ,
	EXPERT_ID             CHAR(20)  NULL ,
	EMPLYR_ID             VARCHAR2(20)  NULL ,
	KNWLDG_NM             VARCHAR2(60)  NULL ,
	KNWLDG_CN             VARCHAR2(2500)  NULL ,
	KWRD                  VARCHAR2(100)  NULL ,
	OTHBC_AT              CHAR(1)  NULL ,
	KNWLDG_EVL            CHAR(1)  NULL ,
	COLCT_DE              CHAR(20)  NULL ,
	EVL_DE                CHAR(20)  NULL ,
	ATCH_FILE_ID          CHAR(20)  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	DSUSE_DE              CHAR(20)  NULL ,
CONSTRAINT  COMTNDAMKNOIFM_PK PRIMARY KEY (KNWLDG_ID)
);


CREATE TABLE COMTNDAMMAPKNO
(
	KNWLDG_TY_CODE        VARCHAR2(3)  NOT NULL ,
	ORGNZT_ID             CHAR(20)  NULL ,
	EXPERT_ID             CHAR(20)  NULL ,
	KNWLDG_TY_NM          VARCHAR2(60)  NULL ,
	CL_DE                 CHAR(20)  NULL ,
	KNWLDG_URL            VARCHAR2(255)  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
CONSTRAINT  COMTNDAMMAPKNO_PK PRIMARY KEY (KNWLDG_TY_CODE)
);

CREATE TABLE COMTNDAMPRO
(
	EXPERT_ID             CHAR(20)  NOT NULL ,
	KNWLDG_TY_CODE        VARCHAR2(3)  NOT NULL ,
	EXPERT_GRAD           CHAR(1)  NOT NULL ,
	EXPERT_CONFM_DE       CHAR(20)  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	EXPERT_DC             VARCHAR2(2000)  NULL ,
CONSTRAINT  COMTNDAMPRO_PK PRIMARY KEY (EXPERT_ID,KNWLDG_TY_CODE,EXPERT_GRAD),
CONSTRAINT  COMTNDAMPRO_FK1 FOREIGN KEY (KNWLDG_TY_CODE) REFERENCES COMTNDAMMAPKNO(KNWLDG_TY_CODE)
);

CREATE TABLE INFRML_SANCTN
(
	INFRML_SANCTN_ID      CHAR(20)  NOT NULL ,
	JOB_SE_CODE           CHAR(3)  NOT NULL ,
	APPLCNT_ID            VARCHAR2(20)  NOT NULL ,
	REQST_DE              CHAR(20)  NOT NULL ,
	SANCTNER_ID           VARCHAR2(20)  NOT NULL ,
	CONFM_AT              CHAR(1)  NOT NULL ,
	SANCTN_DT             DATE  NULL ,
	RETURN_RESN           VARCHAR2(1000)  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
CONSTRAINT  INFRML_SANCTN_PK PRIMARY KEY (INFRML_SANCTN_ID)
);
CREATE TABLE DB_MNTRNG
(
	DATA_SOURC_NM         VARCHAR2(60)  NOT NULL ,
	SERVER_NM             VARCHAR2(60)  NULL ,
	DBMS_KND              VARCHAR2(2)  NULL ,
	CECK_SQL              VARCHAR2(250)  NULL ,
	MNGR_NM               VARCHAR2(60)  NULL ,
	MNGR_EMAIL_ADRES      VARCHAR2(50)  NULL ,
	MNTRNG_STTUS          CHAR(2)  NULL ,
	CREAT_DT              DATE  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NOT NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NOT NULL ,
CONSTRAINT  DB_MNTRNG_PK PRIMARY KEY (DATA_SOURC_NM)
);

CREATE TABLE COMTNTRSMRCV_MNTRNG
(
	CNTC_ID               CHAR(8)  NOT NULL ,
	TEST_CLASS_NM         VARCHAR2(255)  NULL ,
	MNGR_NM               VARCHAR2(60)  NULL ,
	MNGR_EMAIL_ADRES      VARCHAR2(50)  NULL ,
	MNTRNG_STTUS          CHAR(2)  NULL ,
	CREAT_DT              DATE  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NOT NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NOT NULL ,
CONSTRAINT  COMTNTRSMRCV_MNTRNG_PK PRIMARY KEY (CNTC_ID)
);


CREATE TABLE DEPT_JOB
(
	DEPT_JOB_ID           CHAR(20)  NOT NULL ,
	DEPT_JOBBX_ID         CHAR(6)  NOT NULL ,
	DEPT_JOB_NM           VARCHAR2(255)  NOT NULL ,
	DEPT_JOB_CN           VARCHAR2(2500)  NOT NULL ,
	ATCH_FILE_ID          CHAR(20)  NULL ,
	CHARGER_ID            VARCHAR2(20)  NOT NULL ,
	PRIORT                CHAR(1)  NOT NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NOT NULL ,
	FRST_REGIST_PNTTM     DATE  NOT NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
CONSTRAINT  DEPT_JOB_PK PRIMARY KEY (DEPT_JOB_ID)
);

CREATE TABLE LEADER_SCHDUL
(
	SCHDUL_ID             CHAR(20)  NOT NULL ,
	SCHDUL_SE             CHAR(1)  NULL ,
	SCHDUL_NM             VARCHAR2(255)  NOT NULL ,
	SCHDUL_CN             VARCHAR2(2500)  NOT NULL ,
	SCHDUL_PLACE          VARCHAR2(255)  NULL ,
	LEADER_ID             VARCHAR2(20)  NOT NULL ,
	REPTIT_SE_CODE        CHAR(1)  NULL ,
	SCHDUL_BGNDE          CHAR(20)  NULL ,
	SCHDUL_ENDDE          CHAR(20)  NULL ,
	SCHDUL_CHARGER_ID     VARCHAR2(20)  NOT NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NOT NULL ,
	FRST_REGIST_PNTTM     DATE  NOT NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
CONSTRAINT  LEADER_SCHDUL_PK PRIMARY KEY (SCHDUL_ID)
);

CREATE TABLE LEADER_SCHDUL_DE
(
	SCHDUL_ID             CHAR(20)  NOT NULL ,
	SCHDUL_DE             CHAR(8)  NOT NULL ,
CONSTRAINT  LEADER_SCHDUL_DE_PK PRIMARY KEY (SCHDUL_ID,SCHDUL_DE),
CONSTRAINT  LEADER_SCHDUL_DE_FK1 FOREIGN KEY (SCHDUL_ID) REFERENCES LEADER_SCHDUL(SCHDUL_ID)
);
CREATE TABLE LEADER_STTUS
(
	LEADER_ID             VARCHAR2(20)  NOT NULL ,
	LEADER_STTUS          CHAR(1)  NOT NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
CONSTRAINT  LEADER_STTUS_PK PRIMARY KEY (LEADER_ID)
);
CREATE TABLE DEPT_JOBBX
(
	DEPT_JOBBX_ID         CHAR(6)  NOT NULL ,
	DEPT_JOBBX_NM         VARCHAR2(255)  NOT NULL ,
	DEPT_ID               VARCHAR2(20)  NOT NULL ,
	INDICT_ORDR           NUMBER(6)  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NOT NULL ,
	FRST_REGIST_PNTTM     DATE  NOT NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
CONSTRAINT  DEPT_JOBBX_PK PRIMARY KEY (DEPT_JOBBX_ID)
);

CREATE TABLE DTA_USE_STATS
(
	DTA_USE_STATS_ID      CHAR(20)  NOT NULL ,
	BBS_ID                CHAR(20)  NOT NULL ,
	NTT_ID                NUMBER(20)  NOT NULL ,
	ATCH_FILE_ID          CHAR(20)  NOT NULL ,
	FILE_SN               NUMBER(10)  NOT NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
CONSTRAINT  DTA_USE_STATS_PK PRIMARY KEY (DTA_USE_STATS_ID)
);

CREATE TABLE INSTT_CODE
(
	INSTT_CODE            CHAR(7)  NOT NULL ,
	ALL_INSTT_NM          VARCHAR2(255)  NULL ,
	LOWEST_INSTT_NM       VARCHAR2(100)  NULL ,
	INSTT_ABRV_NM         VARCHAR2(50)  NULL ,
	ODR                   CHAR(1)  NULL ,
	ORD                   CHAR(3)  NULL ,
	INSTT_ODR             CHAR(2)  NULL ,
	UPPER_INSTT_CODE      CHAR(7)  NULL ,
	BEST_INSTT_CODE       CHAR(7)  NULL ,
	REPRSNT_INSTT_CODE    CHAR(7)  NULL ,
	INSTT_TY_LCLAS        CHAR(2)  NULL ,
	INSTT_TY_MLSFC        CHAR(2)  NULL ,
	INSTT_TY_SCLAS        CHAR(2)  NULL ,
	TELNO                 VARCHAR2(20)  NULL ,
	FXNUM                 VARCHAR2(20)  NULL ,
	CREAT_DE              CHAR(20)  NULL ,
	ABL_DE                CHAR(20)  NULL ,
	ABL_ENNC              CHAR(1)  NULL ,
	CHANGE_DE             CHAR(20)  NULL ,
	CHANGE_TIME           VARCHAR2(6)  NULL ,
	BSIS_DE               CHAR(20)  NULL ,
	SORT_ORDR             NUMBER(8)  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
CONSTRAINT  INSTT_CODE_PK PRIMARY KEY (INSTT_CODE)
);

CREATE TABLE INSTT_CODE_RECPTN_LOG
(
	OCCRRNC_DE            CHAR(20)  NOT NULL ,
	INSTT_CODE            CHAR(7)  NOT NULL ,
	OPERT_SN              NUMBER(10)  NOT NULL ,
	CHANGE_SE_CODE        VARCHAR2(2)  NULL ,
	PROCESS_SE            VARCHAR2(2)  NULL ,
	ETC_CODE              CHAR(2)  NULL ,
	ALL_INSTT_NM          VARCHAR2(255)  NULL ,
	LOWEST_INSTT_NM       VARCHAR2(100)  NULL ,
	INSTT_ABRV_NM         VARCHAR2(50)  NULL ,
	ODR                   CHAR(1)  NULL ,
	ORD                   CHAR(3)  NULL ,
	INSTT_ODR             CHAR(2)  NULL ,
	UPPER_INSTT_CODE      CHAR(7)  NULL ,
	BEST_INSTT_CODE       CHAR(7)  NULL ,
	REPRSNT_INSTT_CODE    CHAR(7)  NULL ,
	INSTT_TY_LCLAS        CHAR(2)  NULL ,
	INSTT_TY_MLSFC        CHAR(2)  NULL ,
	INSTT_TY_SCLAS        CHAR(2)  NULL ,
	TELNO                 VARCHAR2(20)  NULL ,
	FXNUM                 VARCHAR2(20)  NULL ,
	CREAT_DE              CHAR(20)  NULL ,
	ABL_DE                CHAR(20)  NULL ,
	ABL_ENNC              CHAR(1)  NULL ,
	CHANGE_DE             CHAR(20)  NULL ,
	CHANGE_TIME           VARCHAR2(6)  NULL ,
	BSIS_DE               CHAR(20)  NULL ,
	SORT_ORDR             NUMBER(8)  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
CONSTRAINT  INSTT_CODE_RECPTN_LOG_PK PRIMARY KEY (OCCRRNC_DE,INSTT_CODE,OPERT_SN)
);

CREATE TABLE INDVDL_YRYC_MANAGE
(
	OCCRRNC_YEAR          CHAR(4)  NOT NULL ,
	YRYC_OCCRRNC_CO       NUMBER(5,1)  NULL ,
	USE_YRYC_CO           NUMBER(5,1)  NULL ,
	REMNDR_YRYC_CO        NUMBER(5,1)  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	USER_ID               VARCHAR2(20)  NOT NULL ,
CONSTRAINT  INDVDL_YRYC_MANAGE_PK PRIMARY KEY (OCCRRNC_YEAR,USER_ID)
);

CREATE TABLE NTWRK_SVC_MNTRNG
(
	SYS_IP                VARCHAR2(23)  NOT NULL ,
	SYS_PORT              NUMBER(5)  NOT NULL ,
	SYS_NM                VARCHAR2(255)  NOT NULL ,
	MNGR_NM               VARCHAR2(60)  NULL ,
	MNGR_EMAIL_ADRES      VARCHAR2(50)  NULL ,
	MNTRNG_STTUS          CHAR(2)  NULL ,
	CREAT_DT              DATE  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NOT NULL ,
	LAST_UPDT_PNTTM       DATE  NOT NULL ,
CONSTRAINT  NTWRK_SVC_MNTRNG_PK PRIMARY KEY (SYS_IP,SYS_PORT)
);


CREATE TABLE NTWRK_SVC_MNTRNG_LOG
(
	SYS_IP                VARCHAR2(23)  NOT NULL ,
	SYS_PORT              NUMBER(5)  NOT NULL ,
	SYS_NM                VARCHAR2(255)  NOT NULL ,
	MNTRNG_STTUS          CHAR(2)  NULL ,
	LOG_INFO              VARCHAR2(2000)  NULL ,
	CREAT_DT              DATE  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NOT NULL ,
	LAST_UPDT_PNTTM       DATE  NOT NULL ,
	LOG_ID                CHAR(20)  NOT NULL ,
CONSTRAINT  NTWRK_SVC_MNTRNG_LOG_PK PRIMARY KEY (SYS_IP,SYS_PORT,LOG_ID),
CONSTRAINT  NTWRK_SVC_MNTRNG_LOG_FK2 FOREIGN KEY (SYS_IP,SYS_PORT) REFERENCES NTWRK_SVC_MNTRNG(SYS_IP,SYS_PORT)
);

CREATE TABLE SERVER_EQPMN
(
	SERVER_EQPMN_ID       VARCHAR2(20)  NOT NULL ,
	SERVER_EQPMN_NM       VARCHAR2(60)  NULL ,
	SERVER_EQPMN_IP       VARCHAR2(23)  NULL ,
	SERVER_EQPMN_MNGR     VARCHAR2(60)  NULL ,
	MNGR_EMAIL_ADRES      VARCHAR2(50)  NULL ,
	OPERSYSM_INFO         VARCHAR2(2000)  NULL ,
	CPU_INFO              VARCHAR2(2000)  NULL ,
	MORY_INFO             VARCHAR2(2000)  NULL ,
	HDDISK                CHAR(18)  NULL ,
	ETC_INFO              VARCHAR2(250)  NULL ,
	RGSDE                 DATE  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
CONSTRAINT  SERVER_EQPMN_PK PRIMARY KEY (SERVER_EQPMN_ID)
);

CREATE TABLE SYNCHRN_SERVER
(
	SERVER_ID             CHAR(20)  NOT NULL ,
	SERVER_NM             VARCHAR2(60)  NULL ,
	SERVER_IP             VARCHAR2(23)  NULL ,
	SERVER_PORT           VARCHAR2(10)  NULL ,
	FTP_ID                VARCHAR2(20)  NULL ,
	FTP_PASSWORD          VARCHAR2(20)  NULL ,
	SYNCHRN_LC            VARCHAR2(255)  NULL ,
	REFLCT_AT             CHAR(1)  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
CONSTRAINT  SYNCHRN_SERVER_PK PRIMARY KEY (SERVER_ID)
);
CREATE TABLE SERVER
(
	SERVER_ID             CHAR(20)  NOT NULL ,
	SERVER_NM             VARCHAR2(60)  NULL ,
	SERVER_KND            CHAR(2)  NULL ,
	RGSDE                 DATE  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
CONSTRAINT  SERVER_PK PRIMARY KEY (SERVER_ID)
);

CREATE TABLE SERVER_EQPMN_RELATE
(
	SERVER_EQPMN_ID       VARCHAR2(20)  NOT NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	SERVER_ID             CHAR(20)  NOT NULL ,
CONSTRAINT  SERVER_EQPMN_RELATE_PK PRIMARY KEY (SERVER_EQPMN_ID,SERVER_ID),
CONSTRAINT  SERVER_EQPMN_RELATE_FK2 FOREIGN KEY (SERVER_EQPMN_ID) REFERENCES SERVER_EQPMN(SERVER_EQPMN_ID),
CONSTRAINT  SERVER_EQPMN_RELATE_FK1 FOREIGN KEY (SERVER_ID) REFERENCES SERVER(SERVER_ID)
);

CREATE TABLE SERVER_RESRCE_LOG
(
	SERVER_EQPMN_ID       VARCHAR2(20)  NOT NULL ,
	CPU_USE_RT            NUMBER(3)  NULL ,
	MORY_USE_RT           NUMBER(3)  NULL ,
	SVC_STTUS             CHAR(2)  NULL ,
	LOG_INFO              VARCHAR2(2000)  NULL ,
	CREAT_DT              DATE  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	SERVER_ID             CHAR(20)  NOT NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	LOG_ID                CHAR(20)  NOT NULL ,
CONSTRAINT  SERVER_RESRCE_LOG_PK PRIMARY KEY (SERVER_EQPMN_ID,SERVER_ID,LOG_ID),
CONSTRAINT  SERVER_RESRCE_LOG_FK1 FOREIGN KEY (SERVER_EQPMN_ID,SERVER_ID) REFERENCES SERVER_EQPMN_RELATE(SERVER_EQPMN_ID,SERVER_ID)
);

CREATE TABLE VCATN_MANAGE
(
	APPLCNT_ID            VARCHAR2(20)  NOT NULL ,
	VCATN_SE              CHAR(2)  NOT NULL ,
	BGNDE                 CHAR(8)  NOT NULL ,
	ENDDE                 CHAR(8)  NOT NULL ,
	VCATN_RESN            VARCHAR2(200)  NOT NULL ,
	REQST_DE              CHAR(20)  NOT NULL ,
	OCCRRNC_YEAR          CHAR(4)  NULL ,
	SANCTNER_ID           VARCHAR2(20)  NULL ,
	CONFM_AT              CHAR(1)  NULL ,
	SANCTN_DT             DATE  NULL ,
	RETURN_RESN           VARCHAR2(1000)  NULL ,
	INFRML_SANCTN_ID      CHAR(20)  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	NOON_SE               CHAR(1)  NULL ,
CONSTRAINT  VCATN_MANAGE_PK PRIMARY KEY (APPLCNT_ID,VCATN_SE,BGNDE,ENDDE)
);


CREATE TABLE MEMO_TODO
(
	TODO_ID               CHAR(20)  NOT NULL ,
	TODO_SJ               VARCHAR2(255)  NOT NULL ,
	TODO_BEGIN_TIME       VARCHAR2(14)  NOT NULL ,
	TODO_END_TIME         VARCHAR2(14)  NOT NULL ,
	WRTER_ID              VARCHAR2(20)  NOT NULL ,
	TODO_CN               VARCHAR2(2500)  NOT NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NOT NULL ,
	FRST_REGIST_PNTTM     DATE  NOT NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
CONSTRAINT  MEMO_TODO_PK PRIMARY KEY (TODO_ID)
);

CREATE TABLE NOTE
(
	NOTE_ID               CHAR(20)  NOT NULL ,
	NOTE_SJ               VARCHAR2(255)  NULL ,
	NOTE_CN               VARCHAR2(4000)  NULL ,
	ATCH_FILE_ID          CHAR(20)  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
CONSTRAINT  NOTE_PK PRIMARY KEY (NOTE_ID)
);


CREATE TABLE NOTE_TRNSMIT
(
	NOTE_ID               CHAR(20)  NOT NULL ,
	NOTE_TRNSMIT_ID       CHAR(20)  NOT NULL ,
	TRNSMITER_ID          CHAR(20)  NULL ,
	DELETE_AT             CHAR(8)  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
CONSTRAINT  NOTE_TRNSMIT_PK PRIMARY KEY (NOTE_ID,NOTE_TRNSMIT_ID),
CONSTRAINT  NOTE_TRNSMIT_FK1 FOREIGN KEY (NOTE_ID) REFERENCES NOTE(NOTE_ID)
);

CREATE TABLE NOTE_RECPTN
(
	NOTE_ID               CHAR(20)  NOT NULL ,
	NOTE_TRNSMIT_ID       CHAR(20)  NOT NULL ,
	NOTE_RECPTN_ID        CHAR(20)  NOT NULL ,
	RCVER_ID              CHAR(20)  NULL ,
	OPEN_YN               CHAR(1)  NULL ,
	RECPTN_SE             CHAR(1)  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
CONSTRAINT  NOTE_RECPTN_PK PRIMARY KEY (NOTE_ID,NOTE_TRNSMIT_ID,NOTE_RECPTN_ID),
CONSTRAINT  NOTE_RECPTN_FK1 FOREIGN KEY (NOTE_ID,NOTE_TRNSMIT_ID) REFERENCES NOTE_TRNSMIT(NOTE_ID,NOTE_TRNSMIT_ID)
);

CREATE TABLE EVENT_MANAGE
(
	EVENT_ID              CHAR(20)  NOT NULL ,
	EVENT_SE              VARCHAR2(2)  NOT NULL ,
	EVENT_NM              VARCHAR2(60)  NOT NULL ,
	EVENT_PURPS           VARCHAR2(200)  NOT NULL ,
	EVENT_BGNDE           CHAR(20)  NOT NULL ,
	EVENT_ENDDE           CHAR(20)  NOT NULL ,
	EVENT_AUSPC_INSTT_NM  VARCHAR2(60)  NULL ,
	EVENT_MNGT_INSTT_NM   VARCHAR2(60)  NULL ,
	EVENT_PLACE           VARCHAR2(200)  NOT NULL ,
	EVENT_CN              VARCHAR2(1000)  NULL ,
	CT_OCCRRNC_AT         CHAR(1)  NULL ,
	PARTCPT_CT            NUMBER(16)  NULL ,
	PSNCPA                NUMBER(10)  NOT NULL ,
	REFRN_URL             VARCHAR2(1024)  NULL ,
	RCEPT_BGNDE           CHAR(20)  NOT NULL ,
	RCEPT_ENDDE           CHAR(20)  NOT NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
CONSTRAINT  EVENT_MANAGE_PK PRIMARY KEY (EVENT_ID)
);


CREATE TABLE EVENT_AT_DRN
(
	APPLCNT_ID            VARCHAR2(20)  NOT NULL ,
	EVENT_ID              CHAR(20)  NOT NULL ,
	REQST_DE              CHAR(20)  NOT NULL ,
	SANCTNER_ID           VARCHAR2(20)  NOT NULL ,
	CONFM_AT              CHAR(1)  NULL ,
	SANCTN_DT             DATE  NULL ,
	RETURN_RESN           VARCHAR2(1000)  NULL ,
	INFRML_SANCTN_ID      CHAR(20)  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
CONSTRAINT  EVENT_AT_DRN_PK PRIMARY KEY (APPLCNT_ID,EVENT_ID),
CONSTRAINT  EVENT_AT_DRN_FK1 FOREIGN KEY (EVENT_ID) REFERENCES EVENT_MANAGE(EVENT_ID)
);


CREATE TABLE IMG_TEMP
(
	ORGNZT_CODE           VARCHAR2(10)  NOT NULL ,
	ERNCSL_SE             VARCHAR2(2)  NOT NULL ,
	IMAGE_INFO            BLOB  NOT NULL ,
	IMAGE_TY              VARCHAR2(20)  NULL ,
CONSTRAINT  IMG_TEMP_PK PRIMARY KEY (ORGNZT_CODE,ERNCSL_SE)
);


CREATE TABLE WIK_MNTHNG_REPRT
(
	REPRT_ID              CHAR(6)  NOT NULL ,
	REPRT_SE              CHAR(1)  NOT NULL ,
	REPRT_SJ              VARCHAR2(255)  NOT NULL ,
	REPORT_DE             CHAR(20)  NOT NULL ,
	WRTER_ID              VARCHAR2(20)  NOT NULL ,
	REPORTR_ID            VARCHAR2(20)  NOT NULL ,
	REPORT_BGNDE          CHAR(20)  NOT NULL ,
	REPORT_ENDDE          CHAR(20)  NOT NULL ,
	THSWIK_REPORT_CN      CLOB  NOT NULL ,
	NEXTWIK_REPORT_CN     CLOB  NOT NULL ,
	PARTCLR_MATTER        VARCHAR2(2500)  NULL ,
	ATCH_FILE_ID          CHAR(20)  NULL ,
	CONFM_DT              VARCHAR2(14)  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NOT NULL ,
	FRST_REGIST_PNTTM     DATE  NOT NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
CONSTRAINT  WIK_MNTHNG_REPRT_PK PRIMARY KEY (REPRT_ID)
);

CREATE TABLE TWITTER
(
	USER_ID               VARCHAR2(20)  NOT NULL ,
	CNSMR_KEY             VARCHAR2(50)  NOT NULL ,
	CNSMR_SECRET          VARCHAR2(50)  NOT NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
CONSTRAINT  TWITTER_PK PRIMARY KEY (USER_ID)
);

CREATE TABLE WIKI_BKMK
(
	WIKI_BKMK_ID          CHAR(20)  NOT NULL ,
	USER_ID               VARCHAR2(20)  NOT NULL ,
	WIKI_BKMK_NM          VARCHAR2(1000)  NOT NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
CONSTRAINT  WIKI_BKMK_PK PRIMARY KEY (WIKI_BKMK_ID,USER_ID),
CONSTRAINT  WIKI_BKMK_FK1 FOREIGN KEY (USER_ID) REFERENCES TWITTER(USER_ID)
);

CREATE TABLE RWARD_MANAGE
(
	RWARD_ID              CHAR(20)  NOT NULL ,
	RWARDWNR_ID           VARCHAR2(20)  NOT NULL ,
	RWARD_CODE            CHAR(2)  NOT NULL ,
	RWARD_DE              CHAR(20)  NOT NULL ,
	RWARD_NM              VARCHAR2(255)  NOT NULL ,
	PBLEN_CN              VARCHAR2(1000)  NULL ,
	SANCTNER_ID           VARCHAR2(20)  NOT NULL ,
	CONFM_AT              CHAR(1)  NULL ,
	SANCTN_DT             DATE  NULL ,
	RETURN_RESN           VARCHAR2(1000)  NULL ,
	ATCH_FILE_ID          CHAR(20)  NULL ,
	INFRML_SANCTN_ID      CHAR(20)  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
CONSTRAINT  RWARD_MANAGE_PK PRIMARY KEY (RWARD_ID)
);

CREATE TABLE RSS
(
	RSS_ID                CHAR(20)  NOT NULL ,
	TRGET_SVC_NM          VARCHAR2(255)  NOT NULL ,
	TRGET_SVC_TABLE       VARCHAR2(255)  NOT NULL ,
	TRGET_SVC_LIST_CO     NUMBER(5)  NOT NULL ,
	HDER_TITLE            VARCHAR2(255)  NOT NULL ,
	HDER_LINK             VARCHAR2(255)  NOT NULL ,
	HDER_DC               VARCHAR2(4000)  NOT NULL ,
	HDER_TAG              VARCHAR2(255)  NULL ,
	HDER_ETC              VARCHAR2(250)  NULL ,
	BDT_TITLE             VARCHAR2(255)  NULL ,
	BDT_LINK              VARCHAR2(255)  NULL ,
	BDT_DC                VARCHAR2(4000)  NULL ,
	BDT_TAG               VARCHAR2(255)  NULL ,
	BDT_ETC_TAG           VARCHAR2(255)  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
CONSTRAINT  RSS_PK PRIMARY KEY (RSS_ID)
);


CREATE TABLE RESTDE
(
	RESTDE_NO             NUMBER(6)  NOT NULL ,
	RESTDE                CHAR(8)  NULL ,
	RESTDE_NM             VARCHAR2(60)  NULL ,
	RESTDE_DC             VARCHAR2(200)  NULL ,
	RESTDE_SE_CODE        VARCHAR2(2)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
CONSTRAINT  RESTDE_PK PRIMARY KEY (RESTDE_NO)
);

CREATE TABLE PROCESS_MON
(
	PROCS_ID              CHAR(20)  NOT NULL ,
	PROCS_NM              VARCHAR2(60)  NULL ,
	PROCS_STTUS           VARCHAR2(3)  NULL ,
	CREAT_DT              DATE  NULL ,
	MNGR_NM               VARCHAR2(60)  NULL ,
	MNGR_EMAIL_ADRES      VARCHAR2(50)  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
CONSTRAINT  PROCESS_MON_PK PRIMARY KEY (PROCS_ID)
);



CREATE TABLE PROCESS_MON_LOG
(
	PROCS_ID              CHAR(20)  NOT NULL ,
	PROCS_NM              VARCHAR2(60)  NULL ,
	PROCS_STTUS           VARCHAR2(3)  NULL ,
	CREAT_DT              DATE  NULL ,
	LOG_INFO              VARCHAR2(2000)  NULL ,
	MNGR_NM               VARCHAR2(60)  NULL ,
	MNGR_EMAIL_ADRES      VARCHAR2(50)  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	LOG_ID                CHAR(20)  NOT NULL ,
CONSTRAINT  PROCESS_MON_LOG_PK PRIMARY KEY (PROCS_ID,LOG_ID),
CONSTRAINT  PROCESS_MON_LOG_FK2 FOREIGN KEY (PROCS_ID) REFERENCES PROCESS_MON(PROCS_ID)
);


CREATE TABLE NTWRK
(
	NTWRK_ID              CHAR(20)  NOT NULL ,
	NTWRK_IP              VARCHAR2(23)  NULL ,
	GTWY                  VARCHAR2(23)  NULL ,
	SUBNET                VARCHAR2(23)  NULL ,
	DOMN_NM_SERVER        VARCHAR2(23)  NULL ,
	MANAGE_IEM            CHAR(2)  NULL ,
	USER_NM               VARCHAR2(60)  NULL ,
	USE_AT                CHAR(1)  NULL ,
	RGSDE                 DATE  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
CONSTRAINT  NTWRK_PK PRIMARY KEY (NTWRK_ID)
);


CREATE TABLE MEMO_REPRT
(
	REPRT_SJ              VARCHAR2(255)  NOT NULL ,
	REPORT_DE             CHAR(20)  NOT NULL ,
	WRTER_ID              VARCHAR2(20)  NOT NULL ,
	REPORTR_ID            VARCHAR2(20)  NOT NULL ,
	REPORT_CN             VARCHAR2(2500)  NOT NULL ,
	ATCH_FILE_ID          CHAR(20)  NULL ,
	DRCT_MATTER           VARCHAR2(2500)  NULL ,
	DRCT_MATTER_REGIST_DT  VARCHAR2(14)  NULL ,
	REPORTR_INQIRE_DT     VARCHAR2(14)  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NOT NULL ,
	FRST_REGIST_PNTTM     DATE  NOT NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	REPRT_ID              CHAR(6)  NOT NULL ,
CONSTRAINT  MEMO_REPRT_PK PRIMARY KEY (REPRT_ID)
);

CREATE TABLE MTG_PLACE_RESVE
(
	RESVE_ID              CHAR(20)  NOT NULL ,
	MTGRUM_ID             CHAR(20)  NOT NULL ,
	MTG_SJ                VARCHAR2(100)  NOT NULL ,
	RSVCTM_ID             VARCHAR2(20)  NOT NULL ,
	RESVE_DE              CHAR(8)  NOT NULL ,
	RESVE_BEGIN_TM        VARCHAR2(14)  NOT NULL ,
	RESVE_END_TM          VARCHAR2(14)  NOT NULL ,
	ATNDNC_NMPR           NUMBER(10)  NULL ,
	MTG_CN                VARCHAR2(2500)  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
CONSTRAINT  MTG_PLACE_RESVE_PK PRIMARY KEY (RESVE_ID),
CONSTRAINT  MTG_PLACE_RESVE_FK1 FOREIGN KEY (MTGRUM_ID) REFERENCES MTG_PLACE_MANAGE(MTGRUM_ID) ON DELETE SET NULL
);

CREATE TABLE FXTRS_MANAGE
(
	FXTRS_CODE            CHAR(14)  NOT NULL ,
	FXTRS_NM              VARCHAR2(100)  NOT NULL ,
	MAKR_NM               VARCHAR2(100)  NULL ,
	PRICE                 NUMBER(16)  NULL ,
CONSTRAINT  FXTRS_MANAGE_PK PRIMARY KEY (FXTRS_CODE)
);

CREATE TABLE MTG_PLACE_FXTRS
(
	MTGRUM_ID             CHAR(20)  NOT NULL ,
	FXTRS_CODE            CHAR(14)  NOT NULL ,
	QY                    NUMBER(20)  NOT NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
CONSTRAINT  MTG_PLACE_FXTRS_PK PRIMARY KEY (MTGRUM_ID,FXTRS_CODE),
CONSTRAINT  MTG_PLACE_FXTRS_FK2 FOREIGN KEY (MTGRUM_ID) REFERENCES MTG_PLACE_MANAGE(MTGRUM_ID),
CONSTRAINT  MTG_PLACE_FXTRS_FK1 FOREIGN KEY (FXTRS_CODE) REFERENCES FXTRS_MANAGE(FXTRS_CODE)
);
CREATE TABLE COMTECOPSEQ
(
	TABLE_NAME            VARCHAR2(20)  NOT NULL ,
	NEXT_ID               NUMBER(30)  NULL ,
CONSTRAINT  COMTECOPSEQ_PK PRIMARY KEY (TABLE_NAME)
);

CREATE TABLE ANNVRSRY_MANAGE
(
	ANNVRSRY_ID           VARCHAR2(20)  NOT NULL ,
	USER_ID               VARCHAR2(20)  NOT NULL ,
	ANNVRSRY_SE           VARCHAR2(2)  NOT NULL ,
	ANNVRSRY_NM           VARCHAR2(255)  NOT NULL ,
	ANNVRSRY              CHAR(20)  NOT NULL ,
	CLDR_SE               CHAR(1)  NOT NULL ,
	ANNVRSRY_NTCN_SETUP   CHAR(1)  NULL ,
	ANNVRSRY_NTCN_BGNDE   CHAR(20)  NULL ,
	MEMO                  VARCHAR2(1000)  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	REPTIT_AT             CHAR(1)  NULL ,
CONSTRAINT  ANNVRSRY_MANAGE_PK PRIMARY KEY (ANNVRSRY_ID)
);

CREATE TABLE J_ATCH_FILE 
(
	FILE_ID VARCHAR2(13) NOT NULL,
	FILE_SEQ INTEGER NOT NULL,
	FILE_NAME VARCHAR2(100) NOT NULL,
	FILE_SIZE INTEGER,
	FILE_MASK VARCHAR2(100),
	DOWNLOAD_COUNT INTEGER,
	DOWNLOAD_EXPIRE_DATE VARCHAR2(8),
	DOWNLOAD_LIMIT_COUNT INTEGER,
	REG_DATE DATE,
	DELETE_YN VARCHAR2(1),
CONSTRAINT  J_ATCH_FILE_PK PRIMARY KEY (FILE_ID, FILE_SEQ)
);

CREATE TABLE ROUGH_MAP (
    ROUGHMAP_ID       VARCHAR(75)   NOT NULL,
    ROUGHMAPSJ        VARCHAR(75)   NOT NULL,
    ROUGHMAPADDRESS   VARCHAR(200)  NULL,
    LA                VARCHAR(48)   NULL,
    LO                VARCHAR(48)   NULL,
    MARKERLA          VARCHAR(48)   NULL,
    MARKERLO          VARCHAR(48)   NULL,
    INFOWINDOW        VARCHAR(20)   NULL,
    ZOOMLEVEL         VARCHAR(10)   NULL,
    FRST_REGIST_PNTTM DATE          NULL,
    FRST_REGISTER_ID  VARCHAR(20)   NULL,
    LAST_UPDT_PNTTM   DATE          NULL,
    LAST_UPDUSR_ID    VARCHAR(20)   NULL
 );

CREATE TABLE PRIVACY_LOG
(
    REQUST_ID            VARCHAR2(20) NOT NULL,
    INQIRE_DT            DATE NOT NULL,
    SRVC_NM              VARCHAR2(200) NULL,
    INQIRE_INFO          VARCHAR2(100) NULL,
    RQESTER_ID           VARCHAR2(20) NULL,
    RQESTER_IP           VARCHAR2(23) NULL,
CONSTRAINT  REQUST_ID_PK PRIMARY KEY (REQUST_ID)
);
CREATE TABLE COMMUTE (
     WRKTM_ID           CHAR(20) NOT NULL,
     EMPLYR_ID          VARCHAR2(20) NOT NULL,
     ORGNZT_ID          VARCHAR2(20) NULL,
     WRKT_DT            VARCHAR2(10) NOT NULL, 
     WRK_START_TIME     VARCHAR2(14) NULL, 
     WRK_END_TIME       VARCHAR2(14) NULL, 
     WRK_HOURS          CHAR(2) NULL, 
     OVTMWRK_HOURS      CHAR(2) NULL,
     WRK_START_STATUS   VARCHAR2(10) NULL, 
     WRK_END_STATUS     VARCHAR2(10) NULL, 
     RM                 VARCHAR2(100) NULL,
     FRST_REGISTER_ID   VARCHAR2(20) NULL,
     FRST_REGIST_PNTTM  DATE NULL,
     LAST_UPDUSR_ID     VARCHAR2(20) NULL,
     LAST_UPDT_PNTTM    DATE NULL,
 CONSTRAINT COMMUTE_PK  PRIMARY KEY (EMPLYR_ID, WRKT_DT)
);









