DROP TABLE AUTHOR CASCADE CONSTARINTS;
CREATE  TABLE AUTHOR(
	AUTHOR_CODE VARCHAR(30) NOT NULL PRIMARY KEY,
	AUTHOR_NM VARCHAR(60) NOT NULL,
	AUTHOR_DC VARCHAR(200),
	AUTHOR_CREAT_DE CHAR(20) NOT NULL);
DROP TABLE ROLES_HIERARCHY CASCADE CONSTRAINTS;
CREATE TABLE ROLES_HIERARCHY (
  PARNTS_ROLE varchar2(30) NOT NULL,
  CHLDRN_ROLE varchar2(30) NOT NULL,
  CONSTRAINT ROLES_HIERARCHY_PK PRIMARY KEY (PARNTS_ROLE,CHLDRN_ROLE),
  CONSTRAINT ROLES_HIERARCHY_FK_AUTHOR_CHLDRN_ROLE FOREIGN KEY (CHLDRN_ROLE) REFERENCES AUTHOR (AUTHOR_CODE) ON DELETE CASCADE,
  CONSTRAINT ROLES_HIERARCHY_FK_AUTHOR_PARNTS_ROLE FOREIGN KEY (PARNTS_ROLE) REFERENCES AUTHOR (AUTHOR_CODE) ON DELETE CASCADE
) ;	
DROP TABLE ROLE CASCADE CONSTRAINTS;
CREATE TABLE ROLE (
  ROLE_CODE varchar2(50) DEFAULT '' NOT NULL,
  ROLE_NM varchar2(60) NOT NULL,
  ROLE_PTTRN varchar2(300) ,
  ROLE_DC varchar2(200) ,
  ROLE_TY varchar2(80) ,
  ROLE_SORT varchar2(10) ,
  ROLE_CREAT_DE char(20) NOT NULL,
  CONSTRAINT ROLE_PK PRIMARY KEY (ROLE_CODE)
) ;
DROP TABLE AUTHOR_ROLE_RELATE CASCADE CONSTRAINTS;
CREATE TABLE AUTHOR_ROLE_RELATE (
  AUTHOR_CODE varchar2(30) NOT NULL,
  ROLE_CODE varchar2(50) NOT NULL,
  CREAT_DT DATE ,
  CONSTRAINT AUTHOR_ROLE_RELATE_PK PRIMARY KEY (AUTHOR_CODE,ROLE_CODE),
  CONSTRAINT AUTHOR_ROLE_RELATE_FK_ROLE_CODE FOREIGN KEY (ROLE_CODE) REFERENCES ROLE (ROLE_CODE) ON DELETE CASCADE,
  CONSTRAINT AUTHOR_ROLE_RELATE_FK_AUTHOR_CODE FOREIGN KEY (AUTHOR_CODE) REFERENCES AUTHOR (AUTHOR_CODE) ON DELETE CASCADE
) ;
DROP TABLE EMPLYR_SCRTY_ESTBS CASCADE CONSTRAINT;
CREATE  TABLE EMPLYR_SCRTY_ESTBS(
	SCRTY_DTRMN_TRGET_ID VARCHAR(20) NOT NULL PRIMARY KEY,
	MBER_TY_CODE VARCHAR(15),
	AUTHOR_CODE VARCHAR(30) NOT NULL,
	CONSTRAINT EMPLYR_SCRTY_FK_EMPLYR 
		FOREIGN KEY(SCRPT_TRGET_ID) 
		REFERENCES EMPLYR(EMPLYR_ID),
	CONSTRAINT EMPLYR_SCRTY_FK_AUTHOR 
		FOREIGN KEY(AUTHOR_CODE) 
		REFERENCES AUTHOR(AUTHOR_CODE));


DROP TABLE ZIP CASCADE CONSTRAINTS;
CREATE TABLE ZIP (
  ZIP varchar2(6) NOT NULL,
  SN number(10,0) DEFAULT '0' NOT NULL,
  CTPRVN_NM varchar2(20) ,
  SIGNGU_NM varchar2(20) ,
  EMD_NM varchar2(60) ,
  LI_BULD_NM varchar2(60) ,
  LNBR_DONG_HO varchar2(20) ,
  FRST_REGIST_PNTTM DATE ,
  FRST_REGISTER_ID varchar2(20) ,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID varchar2(20) ,
  CONSTRAINT ZIP_PK PRIMARY KEY (ZIP,SN)
) ;

DROP TABLE BANNER CASCADE CONSTRAINTS;
CREATE TABLE BANNER (
  BANNER_ID char(20) DEFAULT '' NOT NULL,
  BANNER_NM varchar2(60) NOT NULL,
  LINK_URL varchar2(255) NOT NULL,
  BANNER_IMAGE varchar2(60) NOT NULL,
  BANNER_DC varchar2(200) ,
  REFLCT_AT char(1) NOT NULL,
  FRST_REGISTER_ID varchar2(20) ,
  FRST_REGIST_PNTTM DATE ,
  LAST_UPDUSR_ID varchar2(20) ,
  LAST_UPDT_PNTTM DATE ,
  BANNER_IMAGE_FILE varchar2(60) ,
  SORT_ORDR number(8,0) ,
  CONSTRAINT BANNER_PK PRIMARY KEY (BANNER_ID)
) ;

DROP TABLE FAQ CASCADE CONSTRAINTS;
CREATE TABLE FAQ (
  FAQ_ID char(20) NOT NULL,
  QESTN_SJ varchar2(255) ,
  QESTN_CN varchar2(2500) ,
  ANSWER_CN varchar2(2500) ,
  RDCNT number(10,0) ,
  FRST_REGIST_PNTTM DATE NOT NULL,
  FRST_REGISTER_ID varchar2(20) NOT NULL,
  LAST_UPDT_PNTTM DATE NOT NULL,
  LAST_UPDUSR_ID varchar2(20) NOT NULL,
  ATCH_FILE_ID char(20) ,
  QNA_PROCESS_STTUS_CODE char(1) ,
  CONSTRAINT FAQ_PK PRIMARY KEY (FAQ_ID),
  CONSTRAINT FAQ_FK_ATCH_FILE FOREIGN KEY (ATCH_FILE_ID) REFERENCES ATCH_FILE (ATCH_FILE_ID)
) ;
DROP TABLE INDVDL_INFO_POLICY CASCADE CONSTRAINTS;
CREATE TABLE INDVDL_INFO_POLICY (
  INDVDL_INFO_POLICY_ID char(20) DEFAULT '' NOT NULL,
  INDVDL_INFO_POLICY_CN varchar2(2500) ,
  INDVDL_INFO_POLICY_AGRE_AT char(1) ,
  FRST_REGISTER_ID varchar2(20) ,
  FRST_REGIST_PNTTM DATE ,
  LAST_UPDUSR_ID varchar2(20) ,
  LAST_UPDT_PNTTM DATE ,
  INDVDL_INFO_POLICY_NM varchar2(255) ,
  CONSTRAINT INDVDL_INFO_POLICY_PK PRIMARY KEY (INDVDL_INFO_POLICY_ID)
) ;
DROP TABLE PROGRM_LIST CASCADE CONSTRAINTS;
CREATE TABLE PROGRM_LIST (
  PROGRM_FILE_NM varchar2(60) DEFAULT '' NOT NULL,
  PROGRM_STRE_PATH varchar2(100) NOT NULL,
  PROGRM_KOREAN_NM varchar2(60) ,
  PROGRM_DC varchar2(200) ,
  URL varchar2(100) NOT NULL,
  CONSTRAINT PROGRM_LIST_PK PRIMARY KEY (PROGRM_FILE_NM)
) ;
DROP TABLE MENU CASCADE CONSTRAINTS;
CREATE TABLE MENU (
  MENU_NM varchar2(60) NOT NULL,
  PROGRM_FILE_NM varchar2(60) NOT NULL,
  MENU_NO number(20,0) NOT NULL,
  UPPER_MENU_NO number(20,0) ,
  MENU_ORDR number(5,0) NOT NULL,
  MENU_DC varchar2(250) ,
  RELATE_IMAGE_PATH varchar2(100) ,
  RELATE_IMAGE_NM varchar2(60) ,
  CONSTRAINT MENU_PK PRIMARY KEY (MENU_NO),
  CONSTRAINT MENU_FK_MENU FOREIGN KEY (UPPER_MENU_NO) REFERENCES MENU (MENU_NO),
  CONSTRAINT MENU_FK_PROGRM_LIST FOREIGN KEY (PROGRM_FILE_NM) REFERENCES PROGRM_LIST (PROGRM_FILE_NM) ON DELETE CASCADE
) ;
DROP TABLE MENU_DETAIL CASCADE CONSTRAINTS;
CREATE TABLE MENU_DETAIL (
  MENU_NO number(20,0) NOT NULL,
  AUTHOR_CODE varchar2(30) NOT NULL,
  MAPNG_CREAT_ID varchar2(30) ,
  CONSTRAINT MENU_DETAIL_PK PRIMARY KEY (MENU_NO,AUTHOR_CODE),
  CONSTRAINT MENU_DETAIL_FK_AUTHOR FOREIGN KEY (AUTHOR_CODE) REFERENCES AUTHOR (AUTHOR_CODE),
  CONSTRAINT MENU_DETAIL_FK_MENU FOREIGN KEY (MENU_NO) REFERENCES MENU (MENU_NO) ON DELETE CASCADE
) ;
DROP TABLE QA CASCADE CONSTRAINTS;
CREATE TABLE QA (
  QA_ID char(20) NOT NULL,
  QESTN_SJ varchar2(255) ,
  QESTN_CN varchar2(2500) ,
  WRITNG_DE char(20) ,
  RDCNT number(10,0) ,
  EMAIL_ADRES varchar2(50) ,
  FRST_REGIST_PNTTM DATE ,
  FRST_REGISTER_ID varchar2(20) ,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID varchar2(20) ,
  QNA_PROCESS_STTUS_CODE char(1) ,
  WRTER_NM varchar2(20) ,
  ANSWER_CN varchar2(2500) ,
  WRITNG_PASSWORD varchar2(20) ,
  ANSWER_DE char(20) ,
  EMAIL_ANSWER_AT char(1) ,
  AREA_NO varchar2(4) ,
  MIDDLE_TELNO varchar2(4) ,
  END_TELNO varchar2(4) ,
  CONSTRAINT QA_PK PRIMARY KEY (QA_ID)
) ;

DROP TABLE QUSTNR_TMPLAT CASCADE CONSTRAINTS;
CREATE TABLE QUSTNR_TMPLAT (
  QUSTNR_TMPLAT_ID char(20) NOT NULL,
  QUSTNR_TMPLAT_TY varchar2(100) ,
  QUSTNR_TMPLAT_DC varchar2(2000) ,
  QUSTNR_TMPLAT_PATH_NM varchar2(100) ,
  FRST_REGIST_PNTTM DATE ,
  FRST_REGISTER_ID varchar2(20) ,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID varchar2(20) ,
  QUSTNR_TMPLAT_IMAGE_INFO blob,
  CONSTRAINT QUSTNR_TMPLAT_PK PRIMARY KEY (QUSTNR_TMPLAT_ID)
) ;

DROP TABLE QESTNR CASCADE CONSTRAINTS;
CREATE TABLE QESTNR (
  QUSTNR_TMPLAT_ID char(20) NOT NULL,
  QESTNR_ID char(20) NOT NULL,
  QUSTNR_SJ varchar2(255) ,
  QUSTNR_PURPS varchar2(1000) ,
  QUSTNR_WRITNG_GUIDANCE_CN varchar2(2000) ,
  QUSTNR_TRGET varchar2(1000) ,
  QUSTNR_BGNDE char(20) ,
  QUSTNR_ENDDE char(20) ,
  FRST_REGIST_PNTTM DATE ,
  FRST_REGISTER_ID varchar2(20) ,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID varchar2(20) ,
  CONSTRAINT QESTNR_PK PRIMARY KEY (QUSTNR_TMPLAT_ID,QESTNR_ID),
  CONSTRAINT QESTNR_FK_QUSTNR_TMPLAT FOREIGN KEY (QUSTNR_TMPLAT_ID) REFERENCES QUSTNR_TMPLAT (QUSTNR_TMPLAT_ID)
) ;
DROP TABLE QUSTNR_QESITM CASCADE CONSTRAINTS;
CREATE TABLE QUSTNR_QESITM (
  QESTNR_ID char(20) NOT NULL,
  QUSTNR_QESITM_ID char(20) NOT NULL,
  QUSTNR_TMPLAT_ID char(20) NOT NULL,
  QESTN_SN number(10,0) ,
  QESTN_TY_CODE char(1) ,
  QESTN_CN varchar2(2500) ,
  MXMM_CHOISE_CO number(5,0) ,
  FRST_REGIST_PNTTM DATE NOT NULL,
  FRST_REGISTER_ID varchar2(20) NOT NULL,
  LAST_UPDT_PNTTM DATE NOT NULL,
  LAST_UPDUSR_ID varchar2(20) NOT NULL,
  CONSTRAINT QUSTNR_QESITM_PK PRIMARY KEY (QESTNR_ID,QUSTNR_QESITM_ID,QUSTNR_TMPLAT_ID),
  CONSTRAINT QUSTNR_QESITM_FK_QESTNR FOREIGN KEY (QUSTNR_TMPLAT_ID, QESTNR_ID) REFERENCES QESTNR (QUSTNR_TMPLAT_ID, QESTNR_ID)
) ;
DROP TABLE QUSTNR_IEM CASCADE CONSTRAINTS;
CREATE TABLE QUSTNR_IEM (
  QUSTNR_TMPLAT_ID char(20) NOT NULL,
  QESTNR_ID char(20) NOT NULL,
  QUSTNR_QESITM_ID char(20) NOT NULL,
  QUSTNR_IEM_ID varchar2(20) NOT NULL,
  IEM_SN number(5,0) ,
  IEM_CN varchar2(1000) ,
  ETC_ANSWER_AT char(1) ,
  FRST_REGIST_PNTTM DATE ,
  FRST_REGISTER_ID varchar2(20) ,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID varchar2(20) ,
  CONSTRAINT QUSTNR_IEM_PK PRIMARY KEY (QUSTNR_TMPLAT_ID,QESTNR_ID,QUSTNR_QESITM_ID,QUSTNR_IEM_ID),
  CONSTRAINT QUSTNR_IEM_FK_QUSTNR_QESIT FOREIGN KEY (QESTNR_ID, QUSTNR_QESITM_ID, QUSTNR_TMPLAT_ID) REFERENCES QUSTNR_QESITM (QESTNR_ID, QUSTNR_QESITM_ID, QUSTNR_TMPLAT_ID)
) ;

DROP TABLE QUSTNR_RESPOND CASCADE CONSTRAINTS;
CREATE TABLE QUSTNR_RESPOND (
  QUSTNR_TMPLAT_ID char(20) NOT NULL,
  QESTNR_ID char(20) NOT NULL,
  QUSTNR_RESPOND_ID char(20) NOT NULL,
  SEXDSTN_CODE char(1) ,
  OCCP_TY_CODE varchar2(1) ,
  RESPOND_NM varchar2(50) ,
  BRTHDY char(20) ,
  AREA_NO varchar2(4) ,
  MIDDLE_TELNO varchar2(4) ,
  END_TELNO varchar2(4) ,
  FRST_REGIST_PNTTM DATE ,
  FRST_REGISTER_ID varchar2(20) ,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID varchar2(20) ,
  CONSTRAINT QUSTNR_RESPOND_PK PRIMARY KEY (QUSTNR_TMPLAT_ID,QESTNR_ID,QUSTNR_RESPOND_ID),
  CONSTRAINT QUSTNR_RESPOND_FK_QESTNR FOREIGN KEY (QUSTNR_TMPLAT_ID, QESTNR_ID) REFERENCES QESTNR (QUSTNR_TMPLAT_ID, QESTNR_ID)
) ;
DROP TABLE QUSTNR_RSPNS_RESULT CASCADE CONSTRAINTS;
CREATE TABLE QUSTNR_RSPNS_RESULT (
  QUSTNR_RSPNS_RESULT_ID char(20) NOT NULL,
  QESTNR_ID char(20) NOT NULL,
  QUSTNR_QESITM_ID char(20) NOT NULL,
  QUSTNR_TMPLAT_ID char(20) NOT NULL,
  RESPOND_ANSWER_CN varchar2(1000) ,
  ETC_ANSWER_CN varchar2(1000) ,
  RESPOND_NM varchar2(50) ,
  FRST_REGIST_PNTTM DATE ,
  FRST_REGISTER_ID varchar2(20) ,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID varchar2(20) ,
  QUSTNR_IEM_ID varchar2(20) ,
  CONSTRAINT QUSTNR_RSPNS_RESULT_PK PRIMARY KEY (QUSTNR_RSPNS_RESULT_ID,QESTNR_ID,QUSTNR_QESITM_ID,QUSTNR_TMPLAT_ID),
  CONSTRAINT QUSTNR_RSPNS_RESULT_FK FOREIGN KEY (QESTNR_ID, QUSTNR_QESITM_ID, QUSTNR_TMPLAT_ID) REFERENCES QUSTNR_QESITM (QESTNR_ID, QUSTNR_QESITM_ID, QUSTNR_TMPLAT_ID)
) ;

DROP TABLE STPLAT CASCADE CONSTRAINTS;
CREATE TABLE STPLAT (
  USE_STPLAT_ID char(20) NOT NULL,
  USE_STPLAT_NM varchar2(100) ,
  USE_STPLAT_CN CLOB,
  INFO_PROVD_AGRE_CN CLOB,
  FRST_REGIST_PNTTM DATE ,
  FRST_REGISTER_ID varchar2(20) ,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID varchar2(20) ,
  CONSTRAINT STPLAT_PK PRIMARY KEY (USE_STPLAT_ID)
) ;



CREATE OR REPLACE VIEW COMVNUSERMASTER ( ESNTL_ID,USER_ID,PASSWORD,USER_NM,USER_ZIP,USER_ADRES,USER_EMAIL,GROUP_ID, USER_SE, ORGNZT_ID ) 
AS  
        SELECT ESNTL_ID, MBER_ID,PASSWORD,MBER_NM,ZIP,ADRES,MBER_EMAIL_ADRES,' ','GNR' AS USER_SE, ' ' ORGNZT_ID
        FROM LETTNGNRLMBER
    UNION ALL
        SELECT ESNTL_ID,EMPLYR_ID,PASSWORD,USER_NM,ZIP,HOUSE_ADRES,EMAIL_ADRES,GROUP_ID ,'USR' AS USER_SE, ORGNZT_ID
        FROM LETTNEMPLYRINFO
    UNION ALL
        SELECT ESNTL_ID,ENTRPRS_MBER_ID,ENTRPRS_MBER_PASSWORD,CMPNY_NM,ZIP,ADRES,APPLCNT_EMAIL_ADRES,' ' ,'ENT' AS USER_SE, ' ' ORGNZT_ID
        FROM LETTNENTRPRSMBER 
;



		
ALTER TABLE EMPLYR_DETAIL 
	ADD CONSTRAINT EMPLYR_DETAIL_FK_EMPLYR 
	FOREIGN KEY(EMPLYR_ID) 
	REFERENCES EMPLYR(EMPLYR_ID);
ALTER TABLE BBS 
	ADD CONSTRAINT BBS_FK_BBS_MASTER 
	FOREIGN KEY(BBS_ID) 
	REFERENCES BBS_MASTER(BBS_ID);
ALTER TABLE EMPLYR
	ADD CONSTRAINT EMPLYR_FK_ENTRPRS_MBER 
	FOREIGN KEY(SCRTY_DTRMN_TRGET_ID) 
	REFERENCES ENTRPRS_MBER(ENTRPRS_MBER_ID);
ALTER TABLE EMPLYR_SCRPT 
	ADD CONSTRAINT EMPLYR_SCRPT 
	FOREIGN KEY(SCRPT_TRGET_ID) REFERENCES GNRL_MBER(MBER_ID);
SET WRITE_DELAY 20;
SET SCHEMA PUBLIC;		